### PR TITLE
Add support for load default path on SSH server

### LINKED ISSUE #1331: Feature: Default path for SFTP connection
It would be fantastic if it was possible to set the default path for a SFTP connection. Right now when I connect to my server I am put in the root / and have to manually go to the directory that I want to browse.

This feature would allow a connection to default to directories other than /, such as always going to the home directory.

### PR DESCRIPTION
**Pull request by TranceLove**
## PR Info

- SftpConnectDialog add textfield for default remote path
- SshConnectionPool.ConnectionInfo updated to allow default path on remote server
- Add test cases for SshConnectionPool.ConnectionInfo and list files on SSH server with HybridFile.getParent(context) as in pressing back button on actual device
- Merge SshClientUtilsTest and SshClientUtilTest

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1331 

#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Fairphone 3
- OS: LineageOS 16.0 (9.0)

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Codacy/PR Quality Review failed.

**Comment by VishalNehra** [comment]
Fixes #1331

**Comment by EmmanuelMess** [comment]
Is this 3.5 or 3.6?

**Comment by EmmanuelMess** [comment]
Updating an existing connection crashed the app.

**Comment by VishalNehra** [comment]
Bot Test comment from pr

**Comment by TranceLove** [comment]
Had found the fix for updating SSH connections, but since it had been staged for 3.6, I'm pulling it off first until the 3.6 branch catches up the changes from 3.5. Meanwhile will try adding unit tests...

**Comment by VishalNehra** [comment]
@TranceLove I don't understand.. i thought rename ssh was fixed in 3.5? I have no problem in including this pr with 3.5 release given it's stable.. i do agree these changes can't be made on 3.6..
But try to avoid taking 3.6 issues before we're done with 3.5.

**Comment by TranceLove** [comment]
build test apk

**Review by VishalNehra — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]

**Pull request merged**
