### PR TITLE
2108: Make services non-sticky; start in foreground

### LINKED ISSUE #2108: Crash on compression
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.2
* OS: Linux Android 11 - 30
* Device: raphaelin
* Model: Redmi K20 Pro
* Product: evolution_raphael
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.ExtractService@7593294 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
 at android.app.ActivityThread.access$1800(ActivityThread.java:237)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7661)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
 at com.amaze.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:96)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
 ... 8 more

</details>
<hr>

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2108
-or-   
Addresses #

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Why this change, are we certain the operations will finish correctly now? What if the phone runs out of resources?

**Comment by VishalNehra** [comment]
We're not certain the operations will not crash, that's why this is fail fast way of exiting service as soon as we have a crash.
As for low resources scenario, we do need it to be rescheduled.

If it is stopped due to crash, there's no point in rescheduling it, so better show the crash to the user (that's what this PR aims to deliver).
If it is stopped due to low memory, we need to reschedule it. 
So in both scenarios we can't depend on system to handle this. 
I shall work on the reschedule part because of low memory in future PR. However for both the scenarios the changes in this PR are necessary.

**Comment by TranceLove** [comment]
Crash when I copy files locally in Pixel 3 emulator running Android 10. Otherwise encrypt/decrypt, zip/unzip, FTP service seem to be running fine.

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.6.0
* __OS:__ Linux Android 10 - 29
* __Device:__ generic_x86
* __Model:__ Android SDK built for x86
* __Product:__ sdk_gphone_x86

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{38df9c4 u0 com.amaze.filemanager.debug/com.amaze.filemanager.asynchronous.services.CopyService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

Probably related:
https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

**Comment by VishalNehra** [comment]
Yes, we're already calling startForegound in every service class. Not sure why this crash. Did it really take more than 5 secs to reach that call in CopyService? We do have PrepareCopyTask that runs before CopyService. Is that the reason 🤔

**Comment by VishalNehra** [comment]
Very well, seem like this is a problem in Android framework and 5 secs might not be enough to start notification on slower devices. I'm raising new PR reverting the `startForgroundService`

**Comment by VishalNehra** [comment]
https://github.com/TeamAmaze/AmazeFileManager/pull/2191

**Pull request closed without merging**
