### PR TITLE
Bugfix/1942

### LINKED ISSUE #1942: Copy and paste on remote server crashes Amaze
**Describe the bug**
Copy and paste on SSH/SMB server crashes Amaze

**To Reproduce**
1. Create a SFTP/SMB connection in Amaze
2. Click on the the created connection from the drawer
3. Go to folder where you want to copy files from on the server
4. Select some files
5. Tap copy
6. Crash

**Expected behavior**
Should have no crash at all, but the files to copy goes to clipboard, which user should be able to paste afterwards

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: LineageOS 16.0 (community build, date marked 20200625) (9.0)
 - Rooted: Yes
 - Version: 3.5 beta 1

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1942 
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device: Oneplus 6t
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
Use AOP and write annotation to handle non main thread network operations in background, but to return result using blockingGet, so beats the purpose, but until we have a more concrete implementation can utilize this fix.

### CODE REVIEW

**Comment by TranceLove** [comment]
Tested on Fairphone 3 running LineageOS 16.0 (9.0), SMB copy and paste worked, but SSH copy and paste is not. Seems it still hits the NetworkOnMainThreadException error - saw this after turned on printStackTrace().

Anything I need to update SSH related code to match yours?

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
Ahh my bad. Please check on SSH again, as I don't have setup currently on my Mac (:
Also; removed the AOP and switched to typic rx java implementation.

**Comment by TranceLove** [comment]
Copy worked, but cut is still failing.

And regarding failing test cases... will check.

**Comment by TranceLove** [comment]
> Copy worked, but cut is still failing.
> 
> And regarding failing test cases... will check.

Corresponding logcat only had this:

```
2020-09-07 22:30:16.363 23005-23080/com.amaze.filemanager.debug E/SshClientUtils: Error executing template method
    java.lang.NullPointerException: The callable returned a null value
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Meanwhile, my `SftpClientTemplate` did returned null (at line 745) since it's of type `Void`. Perhaps I need to change this?

https://github.com/TeamAmaze/AmazeFileManager/blob/2f8a580d9f098ed383efa8e19055a3e0e0fdb433/app/src/main/java/com/amaze/filemanager/filesystem/HybridFile.java#L728-L746

**Comment by VishalNehra** [comment]
Thanks for fixing this @TranceLove 
Please review as well (:

**Comment by TranceLove** [comment]
Tested again with Fairphone 3 running LineageOS 16.0 (9.0)

Copy using SMB
- device to server: working
- server to device: working
Copy using SFTP
- device to server: working
- server to device: working

Move using SMB
- device to server: working
- server to device: not working
Move using SFTP
- device to server: crash due to NPE
- server to device: not working

It is now known that SFTP support in `MoveFiles` is missing however.

**Comment by VishalNehra** [comment]
Getting following crash for move from SMB to device :
```
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err: jcifs.smb.SmbException: The process cannot access the file because it is being used by another process.
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1457)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1568)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1023)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1539)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
2020-09-09 02:16:00.926 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbFile.delete(SmbFile.java:1523)
2020-09-09 02:16:00.927 26803-29130/com.amaze.filemanager.debug W/System.err:     at jcifs.smb.SmbFile.delete(SmbFile.java:1442)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.filesystem.HybridFile.delete(HybridFile.java:1204)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.DeleteTask.doInBackground(DeleteTask.java:140)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.DeleteTask.doInBackground(DeleteTask.java:54)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-09 02:16:00.928 26803-29130/com.amaze.filemanager.debug W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

You getting the same? And for SFTP also similar crash?

**Comment by TranceLove** [comment]
> You getting the same? And for SFTP also similar crash?

No exception, just nothing happened. But the crash during moving from device to server over SFTP should be caused by lack of implementation... will take care of that.

**Comment by VishalNehra** [comment]
Okay. I have no clue though. Why this error in smb move from server to device 🤔

**Comment by TranceLove** [comment]
> Okay. I have no clue though. Why this error in smb move from server to device thinking

Perhaps it's the leak @EmmanuelMess noticed earlier when bringing jcifs-ng to Amaze. IMO You may want to look for streams that had not been fully closed before deleting the file on the remote, as I read from their [README.md](https://github.com/AgNO3/jcifs-ng/blob/master/README.md)

> For every file handle opened there is now an object which clearly controls it's lifetime (setting aside invalidation by connection errors), namely
> 
> * SmbFileInput/OutputStream
> * SmbRandomAccessFile
> * SmbWatchHandle
> * SmbPipeHandle
> 
> Any of these objects now require that it is explicitly closed - all implement AutoCloseable and therefor can be managed using try-with-resources. If you used to close them through SmbFile.close() that will no longer have the desired effect.

:/

**Comment by VishalNehra** [comment]
I did check the streams are getting closed in GenericCopyUtil. Will check if something need to close any SMB specific stream.
What I don't understand also, how this problem started coming now, as it's doesn't seem to be related to these code changes :/

**Comment by TranceLove** [comment]
Some more observations as the arguments went into `MoveFiles`.

For the files I wish to move from server to device, no matter the `mode` the remote file is, they all went into `OpenMode.FILE` switch case.

I have added a test case for SFTP to show the symptom. Strip the `@Ignore` tag to run the test.

Arguments are weird, but it was what I saw debugging the move action.

Sorry but this is what I can do for the time being - didn't have enough time to check the details and couldn't give you a SMB container to test, but figuring out the arguments into `MoveFiles` maybe the first step to fix the problem.

**Review by EmmanuelMess — APPROVED** [review]
Tests pass, some issues seem to be still here, but we need this for 3.5 beta 2. We'll see of fixing issues as they arise.

**Review by EmmanuelMess — APPROVED** [review]
Tests pass, some issues seem to be still here, but we need this for 3.5 beta 2. We'll see of fixing issues as they arise.

**Pull request merged**
