### PR TITLE
Remove nullCheckOrInterrupt replacing it with better system

### LINKED ISSUE #2289: Code has redundant nullCheckOrInterrupt in LoadFilesListTask
It seems the class has a strong reference to MainFragment and also checks a lot of times if it is null. This should probably be dealt with with a single weak reference, a bunch of strong local references, and only checking for null before long operations.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2289
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@VishalNehra need an NPath complexity issue fixed and a method too long issue fixed, please.

**Comment by TranceLove** [comment]
Should just be fine. Please rebase for the tick ;)

**Review by VishalNehra — APPROVED** [review]

**Comment by EmmanuelMess** [comment]
@TranceLove already rebased

**Comment by EmmanuelMess** [comment]
@VishalNehra this should have been merged under the 30 day 1 approval rule.

**Pull request merged**
