### PR TITLE
Make fdroid flavor really conform F-Droid's policy

### PR DESCRIPTION
**Pull request by linsui**
## Description

I removed junrar and cloudrail from fdroid flavor. cloudrail is added as a stub based on https://github.com/foobnix/LibreraReader/tree/master/app/src/fdroid/java/com/cloudrail/si.

Builds fine with fdroidserver. https://gitlab.com/linsui/fdroiddata/-/jobs/2746739689

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
@linsui Nice

**Comment by linsui** [comment]
No idea how to fix those test. the fdroid test should fail but I don't know why the play test failed.

**Comment by VishalNehra** [comment]
Why removing com.github.junrar:junrar ? 

Also, please fix following issues:
Codacy
https://app.codacy.com/gh/TeamAmaze/AmazeFileManager/pullRequest?prid=9830092

Spotless (run ./gradlew spotlessCheck to check for formatting errors, and then run ./gradlew spotlessApply to fix them)
https://github.com/TeamAmaze/AmazeFileManager/runs/7428641129?check_suite_focus=true

**Comment by linsui** [comment]
> Why removing com.github.junrar:junrar ?

junrar is licensed under unrar license. See https://fedoraproject.org/wiki/Licensing:Unrar.

**Comment by linsui** [comment]
> Spotless (run ./gradlew spotlessCheck to check for formatting errors, and then run ./gradlew spotlessApply to fix them)

Fixed. It's unrelated to this PR so I reverted it manully. Just apply it again.

**Comment by linsui** [comment]
> The utility class name 'CloudRail' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'

No idea how to fix this.

**Comment by VishalNehra** [comment]
> > The utility class name 'CloudRail' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'
> 
> No idea how to fix this.

It's talking about file name and class name. Make it something like CloudRailHelper or CloudRailUtils

**Comment by linsui** [comment]
It's a stub class. It should have the same name with the one in CloudRail.

**Comment by VishalNehra** [comment]
> It's a stub class. It should have the same name with the one in CloudRail.

Ok. I'll ignore this condition.

**Comment by VishalNehra** [comment]
Can you rebase with release/3.8 again please. Test cases should be fixed.

**Comment by linsui** [comment]
The tests failed with no log...

**Review by VishnuSanal — APPROVED** [review]
Hi! Awesome work! :D 

I tested with `playDebug` flavor, it extracts the RAR file.

On `fdroidDebug`, it throws the an exception from `CompressedHelper#L168`. And, shows a "Cannot process the requested archive" toast on `fdroidRelease` (when 'Extract' button is clicked from the context menu).

But, when the file is clicked (to view it's contents), both on `fdroidDebug` & `fdroidRelease` Amaze reloads the page (when opened from Amaze itself) or opens the home directory (when opened from an external app). (I see this is the default behavior previously too, so it has nothing to do with this PR & is an issue on it's own)

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Addresses #1684

**Comment by VishalNehra** [comment]
How do we go with this now? Do we need to get Amaze enabled on Fdroid by any mod?

**Comment by linsui** [comment]
Is 3.8 ready to go? I can update the F-Droid recipe when you tag a release including this. I'd also like to get https://github.com/TeamAmaze/AmazeFileManager/pull/3414 in but it's not a blocker anyway.

**Comment by VishalNehra** [comment]
> Is 3.8 ready to go? I can update the F-Droid recipe when you tag a release including this. I'd also like to get #3414 in but it's not a blocker anyway.

Thanks. I'll check the other pr and also will update here about 3.8 release.

**Pull request merged**
