### PR TITLE
Fixes #1797 -> Searching more than once will preserve previous search result

### LINKED ISSUE #1797: Searching more than once will preserve previous search result
Bug description
Search result should only show current search result rather than show current and previous result at the same time.

Step to reproduce
1. Input search text
2. Click "search" button
3. Search same text or different text again
4. Search result preserve previous result

Screenshot
Screenshot

Smartphone
360 N6 Pro

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1797 

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
Rotating the device shows nothing.

**Comment by VishalNehra** [comment]
Again, the solution is not to clear the list but to reset the `isResult` flag to false.

**Comment by VishnuSanal** [comment]
> Again, the solution is not to clear the list but to reset the `isResult` flag to false.
> 

Ws mentioned on Telegram, I tried that but didn't work :(

**Comment by EmmanuelMess** [comment]
> Ws mentioned on Telegram, I tried that but didn't work :(

I have not read that conversation, was there anything discussed about clearing the list immediately before putting new values?

**Comment by VishalNehra** [comment]
Superseeded by #2551

**Pull request closed without merging**
