### PR TITLE
2128: Show FAB and expand appbar in empty folder

### LINKED ISSUE #2128: Disspearing FAB
If you move down so that the FAB disspears and enter an empty directory, you can't make the FAB reappear.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2128 
-or-   
Addresses #

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Oneplus 6t
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Review by TranceLove — CHANGES_REQUESTED** [review]
Works with empty folders, but not working yet for folders with content count small enough to __not__ enable scrolling.

Let's say I'm scrolled to make the FAB hide at upper level

Screenshot_20210121-230048_Amaze_Debug

when I enter a folder with only a few items inside, FAB still didn't appear.

Screenshot_20210121-230055_Amaze_Debug

Tested on Fairphone 3 running Lineage OS 16.0 (9.0) and LG Nexus 5x running /e/OS 0.13 (8.1).

**Comment by VishalNehra** [comment]
> when I enter a folder with only a few items inside, FAB still didn't appear.

The only way I see a fix to this is to always make fab visible on any list load. Will that be a good idea?

**Comment by EmmanuelMess** [comment]
> > when I enter a folder with only a few items inside, FAB still didn't appear.
> 
> The only way I see a fix to this is to always make fab visible on any list load. Will that be a good idea?

IMO yes, it should always be shown when the list loads or reloads.

**Comment by VishalNehra** [comment]
@EmmanuelMess Ok

**Review by EmmanuelMess — APPROVED** [review]

**Pull request merged**
