### PR TITLE
Add emulators to CI

### PR DESCRIPTION
**Pull request by EmmanuelMess**
## Description

See https://github.com/marketplace/actions/android-emulator-runner

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@TranceLove is it possible we have two bouncycastle versions?
```
Execution failed for task ':file_operations:mergeDebugAndroidTestJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties' from inputs:
      - /Users/runner/.gradle/caches/transforms-3/92fa7912644cde08f72c3724b3097931/transformed/jetified-bcprov-jdk15on-1.69.jar
      - /Users/runner/.gradle/caches/transforms-3/5b28974e4dfe4c658568efeb4ecd9578/transformed/jetified-bcprov-jdk15to18-1.68.jar
     Adding a packagingOptions block may help, please refer to
     google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

**Comment by VishalNehra** [comment]
@EmmanuelMess See dependency tree? Can exclude from one of the places.

**Comment by EmmanuelMess** [comment]
Are there no tests for android 16?

**Comment by EmmanuelMess** [comment]
The failing test shows that the emulator works, but the test doesn't actually pass any longer.

**Comment by TranceLove** [comment]
> @TranceLove is it possible we have two bouncycastle versions?
> 
> ```
> Execution failed for task ':file_operations:mergeDebugAndroidTestJavaResource'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
>    > 2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties' from inputs:
>       - /Users/runner/.gradle/caches/transforms-3/92fa7912644cde08f72c3724b3097931/transformed/jetified-bcprov-jdk15on-1.69.jar
>       - /Users/runner/.gradle/caches/transforms-3/5b28974e4dfe4c658568efeb4ecd9578/transformed/jetified-bcprov-jdk15to18-1.68.jar
>      Adding a packagingOptions block may help, please refer to
>      google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
>      for more information
> ```

No. But I did hit the same problem before... and yes, I saw you did the module replacement trick on `file_operations` module too.

**Comment by EmmanuelMess** [comment]
@TranceLove @VishalNehra this is ready, some tests don't run and have been momentarily suppressed.

**Comment by EmmanuelMess** [comment]
@TranceLove seems that the tests broke, one too many @Supress where removed.

**Comment by TranceLove** [comment]
> @TranceLove seems that the tests broke, one too many @Supress where removed.

One more try: https://github.com/EmmanuelMess/AmazeFileManager/pull/22

**Comment by EmmanuelMess** [comment]
@TranceLove @VishalNehra this is ready, some tests don't run and have been momentarily suppressed.

**Review by TranceLove — APPROVED** [review]
I'm good to give this a +1.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
