### PR TITLE
Fixed Crash: CompressedExplorerFragment casted to TabFragment #2386

### LINKED ISSUE #2386: Crash: CompressedExplorerFragment casted to TabFragment
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux
HUAWEI/DRA-LX5/HWDRA-MG:8.1.0/HUAWEIDRA-LX5/1.0.0.146(C16):user/release-keys
8.1.0 - 27
* __Device:__ HWDRA-MG
* __Model:__ DRA-LX5
* __Product:__ DRA-LX5
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException:
com.amaze.filemanager.ui.fragments.CompressedExplorerFragment cannot be
cast to com.amaze.filemanager.ui.fragments.TabFragment
at
com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2036)
at
com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
at
com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
at android.view.View.performClick(View.java:6367)
at android.view.View$PerformClick.run(View.java:25040)
at android.os.Handler.handleCallback(Handler.java:795)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:6861)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by wangear**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2386 
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: SM-G965N
- OS: 9.0

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by VishnuSanal** [comment]
@wangear I think you forgot to run `spotlessApply`

**Comment by wangear** [comment]
Thank you for advise.

**Comment by EmmanuelMess** [comment]
Isn't the problem line 868?:
https://github.com/TeamAmaze/AmazeFileManager/blob/d1617b3ca644edb049c6fc51ee10746361aaa00d/app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java#L862-L876

**Comment by wangear** [comment]
@EmmanuelMess  Hm. Sorry. I don't understand. I did exception handling. If you have better idea, I will follow you.

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess Hm. Sorry. I don't understand. I did exception handling. If you have better idea, I will follow you.

Please fix the underlying issue, if that is sensible. Here it would seem that it is the fact that the tab fragment is added with that id.

**Comment by wangear** [comment]
@EmmanuelMess I think "tab" tag is used elsewhere, so I changed "tabt" to "tab". I'm not sure, so please review it. Thank you.

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess I think "tab" tag is used elsewhere, so I changed "tabt" to "tab". I'm not sure, so please review it. Thank you.

I don't quite get the reasoning here.

**Comment by wangear** [comment]
@EmmanuelMess Well. I don't understand what you want. Sorry. If you don't mind, I revert the whole code.

**Comment by VishnuSanal** [comment]
@wangear What happened? Why did you close the PR?

**Comment by wangear** [comment]
I just  don't know  what to do.

**Comment by VishnuSanal** [comment]
@wangear 

> I just don't know what to do.I could not understand what he want.

Please check the comments

> I don't know whole code, and history.

No one knows the whole code base!

> I think this issue is simple bug. But I could not understand his requirement, so I think I not suitable for solving this issue.

Everyone faces this! Try to solve it. If you can't get over, ask for help here or in [our community](https://t.me/AmazeFileManager)

**Comment by wangear** [comment]
Could  you  give  me more detailed explation? I want to know what he wants.
868 line is problem?

**Pull request closed without merging**
