### PR TITLE
Sorting of search results

### PR DESCRIPTION
**Pull request by seelchen**
## Description
This PR adds the ability to sort the search results in the `SearchView`. For this, a button was added to the `SearchView` which opens a dialog similar to the one for sorting directories.

Additionally, to address issue #3357, this PR adds an option to sort the search results by relevance. This sorting is as described in [this comment](https://github.com/TeamAmaze/AmazeFileManager/issues/3357#issuecomment-1813236314) and is only available for sorting search results and not for directories.

To fully resolve issue #3357, the "old" search has to be embedded in the same search view as the new search view.
However, to avoid bloating this PR, I think it might be better to fix that separately.

#### Issue tracker   

Addresses #3357

#### Automatic tests

- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
Device:
- Pixel 7 emulator running Android 13
- HTC U11 life running Android 10

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by seelchen** [comment]
This is ready for review!

**Comment by VishalNehra** [comment]
Yea, descending relevance means least relevant at top and vice versa. I didn't notice this wasn't the original intention.

**Comment by seelchen** [comment]
Alright, then I will invert it :+1:  (although I don't quite understand the logic)

**Comment by VishalNehra** [comment]
It's for the UX, just like you said, it'll be confusing for the user. Not all people using the app are technical, they won't see the relevance as a numerical from less to more. Let's try this way, if we get complaints from user that this behaviour is unexpected, we'll revert to your original implementation.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
