### PR TITLE
Api Level 15 fix color resources

### PR DESCRIPTION
**Pull request by beastlyCoder**
I didn't notice the two resource tags, I have removed them and now everything is working.

Fixes: #1206

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Please don't close PRs and then open another one for the same issue. Just edit the one.

**Comment by EmmanuelMess** [comment]
Why is this is values-v15? I think errors in API 15 are frequently replicable in API 14, but I can't test the latter. This should be in the base values.xml.

**Comment by beastlyCoder** [comment]
Alright duely noted, thank you.

**Comment by EmmanuelMess** [comment]
Also, you can use "Fixes  #xxxx" to autoclose issues after this is merged.

**Comment by beastlyCoder** [comment]
@EmmanuelMess could you give an example of autoclosing an issue please?

**Comment by TranceLove** [comment]
> @EmmanuelMess could you give an example of autoclosing an issue please?

Like this: Fixes #1176

Closing this issue will then autoclose #1176 as well.

**Comment by beastlyCoder** [comment]
So After I commit and make my pull request, i should run that command?

**Comment by TranceLove** [comment]
> So After I commit and make my pull request, i should run that command?

No. Everything is done automagically by github.

**Comment by TranceLove** [comment]
In case you need an example, see my edit at #1202.

**Comment by EmmanuelMess** [comment]
Closing until this is fixed or refuted:
> Why is this is values-v15? I think errors in API 15 are frequently replicable in API 14, but I can't test the latter. This should be in the base values.xml.

**Pull request closed without merging**
