### PR TITLE
Ask MediaScanner to scan received file(s)

### LINKED ISSUE #2801: Mediastore not updated when files are saved using 'send to'
Mediastore not updated when files are saved using 'send to' using external application

### PR DESCRIPTION
**Pull request by Palatis**
Files received by "Send To..." doesn't show in media store immediately.

Scan it/them, so it does!

Fixes #2801

### CODE REVIEW

**Comment by VishalNehra** [comment]
Please point to hotfix/3.6.2 instead of master. Use the issue number  #2801

**Comment by Palatis** [comment]
> 
> 
> Please point to hotfix/3.6.2 instead of master. Use the issue number #2801

done :-D

**Comment by VishnuSanal** [comment]
@Palatis Please run spotless -> `./gradlew spotlessApply`

**Comment by Palatis** [comment]
> 
> 
> @Palatis Please run spotless -> `./gradlew spotlessApply`

done :-D

**Comment by Palatis** [comment]
Ahh damn, what fails this time?

**Comment by VishnuSanal** [comment]
@Palatis It's broken from our side, DW!

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
