### PR TITLE
Configure transifex and update readme

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Configure Transifex file names for regions and update README.

### CODE REVIEW

**Comment by VishalNehra** [comment]
Can you leave a reference, I don;t understand the need for this one.

**Comment by EmmanuelMess** [comment]
> Can you leave a reference, I don;t understand the need for this one.

We don't really need the config file, unless someone wants to use the command line tool, the update to the readme is useful though.

**Comment by EmmanuelMess** [comment]
@VishalNehra Removed config file.

**Comment by EmmanuelMess** [comment]
> Does this change mean that we do not encourage people to make PR for changing translations?

Changing files is already not encouraged.

> What about the changes made in #1707? Will the changes be reverted by Transifex?

Changes to en_US language are updated INTO Transifex, changes to strings in other languages are overwritten.

**Pull request merged**
