### PR TITLE
Fix for displaying files via shortcuts from drawer and fix leak of broadcast event.

### LINKED ISSUE #1916: Documents shortcut does not show any files
Amaze has shortcuts for recent files, images, videos, audio, APKs and documents. The documents shortcut does not show any files. All other shortcuts work as they should.

Phone: Xiaomi Mi 9T Pro
OS: MIUI 12
Amaze version: v3.4.3

### PR DESCRIPTION
**Pull request by pcsaunak**
…ent listener.

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1916
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: oneplus
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Review by TranceLove — DISMISSED** [review]
Works on Oneplus 2 running AOSPExtended (7.1.2) and Fairphone 3 running LineageOS 16.0 (9.0). Document shortcut now displays files after applying changeset. Voting +1.

Well done!

**Comment by VishalNehra** [comment]
Was still getting limited documents. Dug in a bit and found this code 
```
if (docs.size() > 20)
      for (int i = docs.size() - 1; i > 20; i--) {
        docs.remove(i);
      }
```
It's annotated to @TranceLove any specific reason for putting it there? 🤔 
Removing this fixes and getting all 1000 documents I have in my storage.

**Comment by TranceLove** [comment]
> Was still getting limited documents. Dug in a bit and found this code
> 
> ```
> if (docs.size() > 20)
>       for (int i = docs.size() - 1; i > 20; i--) {
>         docs.remove(i);
>       }
> ```
> 
> It's annotated to @TranceLove any specific reason for putting it there? thinking
> Removing this fixes and getting all 1000 documents I have in my storage.

No... it had been there since the beginning... I just renamed the variables without asking "what does it do" 😅️

Never mind... glad we found it.

https://github.com/TeamAmaze/AmazeFileManager/blob/9decb40efa3b9f59724750bf76e2ad415fdf9421/src/main/java/com/amaze/filemanager/services/asynctasks/LoadList.java#L253-L256

**Comment by VishalNehra** [comment]
@pcsaunak please remove the above lines.

**Pull request merged**
