### PR TITLE
Support extracting APK set archives

### LINKED ISSUE #2358: Support extracting APKS
**Is your feature request related to a problem? Please describe.**
Support extracting APK set archives (.apks) which can be generated from an app bundle using bundletool.

**Describe the solution you'd like**
I can extract APK files from an APKS file.

**Describe alternatives you've considered**
APKS files can be renamed to zip to extract it...

**Additional context**
More info about generating APKS can be found here: https://developer.android.com/studio/command-line/bundletool#generate_apks

### PR DESCRIPTION
**Pull request by Unpublished**
## PR Info
Add support for extracting APK set archives (.apks) which can be generated from an app bundle using bundletool.
More info: https://developer.android.com/studio/command-line/bundletool#generate_apks

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2358

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
I don't think extracting *.apk is useful, what usecases does this have?

**Comment by TranceLove** [comment]
> I don't think extracting *.apk is useful, what usecases does this have?

Sometimes, when you want the assets packaged into the apk ;) but not really helpful if the app is a native one, including those written in Unity/Unreal/etc.

**Comment by EmmanuelMess** [comment]
As long as this doesn't affect installing the apk, I would accept it.

**Comment by Unpublished** [comment]
Note that this PR just extends support from APK which is already there to the "new" APKS format which in turn is a zip of (split) APK files.

Usecases stay the same because you need to extract the APK**S** to get the split APK files inside.

> 
> As long as this doesn't affect installing the apk, I would accept it.

Both can still be installed.
APK as normal and APKS require installers like these https://github.com/Aefyr/SAI

**Comment by AnjangMawar** [comment]
>https://github.com/TeamAmaze/AmazeFileManager/projects/4#card-40065m`

**Comment by EmmanuelMess** [comment]
Is there an example we can use to test?

**Comment by Unpublished** [comment]
Sure attached is an APKS file (renamed to zip to be able to upload) containing AmazeFileManager targeting an android emulator.

[AmazeFileManager.zip](https://github.com/TeamAmaze/AmazeFileManager/files/6135707/AmazeFileManager.zip)

**Comment by VishalNehra** [comment]
Please create an issue for this feature request, and mark it to milestone 3.6
I tried the file attached but am unable to get extract option in Amaze after renaming it to amazefilemanager.apks. Am I missing something? 🤔

**Comment by Unpublished** [comment]
Created the issue and referenced it in this PR description, I can't set the milestone tho.
Are you sure you ran this branch while testing? It shows up for me

**Comment by VishalNehra** [comment]
Ahh, my bad. I did take pull but forgot to run, thanks for pointing.

**Review by VishalNehra — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]

**Pull request merged**
