### PR TITLE
How AmazeFileManager works

### PR DESCRIPTION
**Pull request by llrraa**
They may help someone

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Docx and pdf? Why not use formats that are openable from Github?

**Comment by llrraa** [comment]
Is there any easy way to transfer Docx and pdf to formats that are openable from Github? I don't know much about formats that are openable from Github.

**Comment by EmmanuelMess** [comment]
See [the GitHub guide to markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by VishalNehra** [comment]
I think this will be much harder to maintain. We should keep focus on keeping our code clean and write documentation at the place of method definition. 
Again @llrraa please discuss these things before you spend time working on them.

**Comment by llrraa** [comment]
> I think this will be much harder to maintain. We should keep focus on keeping our code clean and write documentation at the place of method definition.
> Again @llrraa please discuss these things before you spend time working on them.

ok

**Comment by EmmanuelMess** [comment]
Will close, if you want you can open another PR or update this one and post a message.

**Comment by llrraa** [comment]
> Will close, if you want you can open another PR or update this one and post a message.

ok, thank you.

**Pull request closed without merging**
