### PR TITLE
Night mode fixed: System theme management added + Daytime using location

### LINKED ISSUE #736: Timed light/dark theme doesn't always coincide with day/night
Currently the code checks for the time (between 6 and 18 is day), I am open to suggestion for better ways to check for day/night.

### PR DESCRIPTION
**Pull request by shayan-mk**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #736
-or-   
Addresses #736

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Google Pixel 3a
- OS: Android API 30

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build failure.
Can you fix formatting? Try `./gradlew spotlessapply`

**Comment by shayan-mk** [comment]
The last version had some issues due to local conflict.
Please check the new version after commit 4b0c5f6.

**Comment by VishnuSanal** [comment]
As an Android user, I would not be interested in a file manager asking me for Location Permission! What do you think @VishalNehra @TranceLove @EmmanuelMess

**Comment by shayan-mk** [comment]
it is optional
you have 3 options other than selecting your light or dark theme directly:
1) use system night mode settings (location not required)
2) use precise night mode using daytime data (requires location)
3) just rely on the hour is between 6 and 18 (location not required )
option #3 is how currently night mode is implemented in the application. if the user does not give the location permission, daytime is calculated using this method.

**Comment by EmmanuelMess** [comment]
> As an Android user, I would not be interested in a file manager asking me for Location Permission! What do you think @VishalNehra @TranceLove @EmmanuelMess

This (getting fine grained position) was a solution from  the start, but its not a solution we can apply on a file manager.

**Comment by EmmanuelMess** [comment]
> it is optional
> you have 3 options other than selecting your light or dark theme directly:
> 
>     1. use system night mode settings (location not required)
> 
>     2. use precise night mode using daytime data (requires location)
> 
>     3. just rely on the hour is between 6 and 18 (location not required )
>        option 3 is how currently night mode is implemented in the application. if the user does not give the location permission, daytime is calculated using this method.

Use the system (when available) and rely on time, do not add location requirement.

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
Remove location requirement

**Comment by TranceLove** [comment]
@EmmanuelMess +1 for no location permission. Even when we are open source, I never want a file manager that acts like some bloated file manager from some authoritarian countries that knows where you are.

Minimal disturbance is all we want - while we already have enough crashes to annoy users. 😔

**Pull request closed without merging**
