### PR TITLE
Fix permission request deny for android M+

### LINKED ISSUE #1866: Runtime permission denial for storage makes trouble
**Runtime permission denial for storage makes trouble**
After showing the permission dialog If I click `Deny & Don't Ask Again`, it continuously showing toast `Permission not granted`. If I stay on the screen for few seconds and exit from app, showing still appears on screen because Toasts could not finish showing all, while the app was open.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app for the first time or every time you click after `Deny & Don't Ask Again` 
2. After showing runtime permission dialog, click `Deny & Don't Ask Again` 
3. Stay for few seconds 
4. Exit the app manually, see that Toast is still there.

**Expected Behaviour**
An extra dialog with **Allow** & **Exit** button can be shown to the user to explain why this app needs storage permission. If the user feels comfortable with this explanation, he can press **Allow** to be directly navigated to the default runtime permission or **Deny** to exit from the app.

**Screenshots**
Amaze

**Smartphone :**
 - Device: Nokia 7 Plus
 - OS:  Android 10
 - Rooted:  No
 - Version: 3.4.3

**Additional context**
You can print the Toast message in the console log and see that it continuously prints that `Permission not granted` message as I've added on that screenshot.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1866 
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Oneplus 6t
- OS: android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #1904 

#### Additional Info

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
Build test apk

**Comment by TranceLove** [comment]
Works at Pixel 2 emulator running Android 10 and Fairphone 3 running LineageOS 16.0 GSI (9.0).

However, the snackbar is overlapping with the software buttons on both devices... can it be placed above the navigation bar?

スクリーンショット 2020-06-15 17-55-38

**Comment by VishalNehra** [comment]
Had to make changes in layouts as well, because as per documentation of [SpeedDial](https://github.com/leinardi/FloatingActionButtonSpeedDial) 
`for the behaviors to work, SpeedDialView needs to be a direct child of CoordinatorLayout`
Otherwise the snackbar was overlapping the FAB.
This will be useful in other areas of Amaze as well.

**Pull request merged**
