### PR TITLE
Migrate FragmentStatePagerAdapter to FragmentStateAdapter

### LINKED ISSUE #2790: Migrate from FragmentStatePagerAdapter to FragmentStateAdapter in TabFragment
Migrate from FragmentStatePagerAdapter to FragmentStateAdapter in TabFragment.

### PR DESCRIPTION
**Pull request by TranceLove**
## Description

- Migrate FragmentStatePagerAdapter in TabFragment to FragmentStateAdapter
- Consequently, remove incompatible DisablableViewPager to ViewPager2
- Consequently, migrate incompatible OnPageChangeListener implementations to ViewPager2.OnPageChangeCallback, which is not interface and needs to be subclassed

Too bad Android X's test framework [doesn't support](https://issuetracker.google.com/issues/121347222) [custom Activities](https://issuetracker.google.com/issues/129030901)... so for test cases, either

- further refactorings at TabFragment to decouple from MainActivity
- use Espresso test, but will raise app's minimal supported version to 4.4 (#3189)

#### Issue tracker   
Fixes #2790

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done
  
- Device: LG Nexus 5x
- OS: LineageOS 17.1 (Android 10)

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
Getting following crash when i rotate my screen

## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager.debug
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/OnePlus9R_IND/OnePlus9R:13/RKQ1.211119.001/R.202209021421:user/release-keys 13 - 33
* __Device:__ OnePlus9R
* __Model:__ LE2101
* __Product:__ OnePlus9R_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{d4f729b} (1154ff16-1173-4291-b775-954eaf77325f tag=f0) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:952)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:247)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0$androidx-fragment-app-FragmentManager(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1280)
	at android.app.Activity.performSaveInstanceState(Activity.java:2239)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1582)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6126)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5516)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6077)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5995)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```
</details>
<hr>

**Comment by TranceLove** [comment]
As the above stacktrace said, MainFragment is not in FragmentManager, so added `onSaveInstanceState()` method back. Let's see how it goes then...

**Comment by VishalNehra** [comment]
I'm still getting following crash if I try to rotate while in lef tab. Right tab seems fine to rotate.

## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager.debug
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/OnePlus9R_IND/OnePlus9R:13/RKQ1.211119.001/R.202209021421:user/release-keys 13 - 33
* __Device:__ OnePlus9R
* __Model:__ LE2101
* __Product:__ OnePlus9R_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: FragmentManager is already executing transactions
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1636)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1666)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(FragmentStateAdapter.java:726)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer$3.onStateChanged(FragmentStateAdapter.java:657)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3058)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2791)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:486)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1529)
	at android.app.Activity.performStart(Activity.java:8416)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3894)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```
</details>
<hr>

**Comment by TranceLove** [comment]
dda2871 should help.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
