### PR TITLE
Add support of 7zip, xz, lzma, and password-protected 7zip and zip files

### LINKED ISSUE #138: Password protected zip files
I don't know how about other password types but at least aes256 password protected zip files are not working

### LINKED ISSUE #163: Support 7-Zip archives
Please add support for 7-Zip (.7z) archives. Preferably also support encrypted ones.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #138, fixes #163, and brings #1222 back.

As said, this is a greedy PR ;)

Changes:
* Backport of commons-compress 7zip support (as separate module) to use FileChannel only, instead of SeekableByteChannel which exists only after Android 8
* Brings #1222 back - last attempt failed due to huge difference between PR and master, so let's try again ;)
* Uses zip4j instead of java.util.zip package, in order to provide support of password-protected zip files
* Refactored `GeneralDialogCreation.showDecryptDialog()` to allow entering archive password uses the same prompt dialog

Not going to think why the previous work by @N00byKing ran without problems - it is possibly caused by upgrading commons-compress library... but anyway.

Tested on Oneplus 2 running Slim7 (7.1.2). Crashed on GPD XD running LegacyRom (4.4.4), but it's because of another problem: [API < 21 does not support vector drawables](https://stackoverflow.com/a/37334176).

```
03-16 21:49:21.940 2864-2864/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager.debug, PID: 2864
    java.lang.RuntimeException: Unable to start service com.amaze.filemanager.asynchronous.services.ExtractService@41d8cbf0 with Intent { cmp=com.amaze.filemanager.debug/com.amaze.filemanager.asynchronous.services.ExtractService (has extras) }: android.content.res.Resources$NotFoundException: File res/drawable/ic_zip_box_grey.xml from drawable resource ID #0x7f0800e8
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2705)
        at android.app.ActivityThread.access$2100(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_zip_box_grey.xml from drawable resource ID #0x7f0800e8
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.support.v4.app.NotificationCompat$Style.createColoredBitmap(NotificationCompat.java:1893)
        at android.support.v4.app.NotificationCompat$Style.createColoredBitmap(NotificationCompat.java:1889)
        at android.support.v4.app.NotificationCompat$Style.applyStandardTemplate(NotificationCompat.java:1805)
        at android.support.v4.app.NotificationCompat$DecoratedCustomViewStyle.createRemoteViews(NotificationCompat.java:3007)
        at android.support.v4.app.NotificationCompat$DecoratedCustomViewStyle.makeContentView(NotificationCompat.java:2963)
        at android.support.v4.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:222)
        at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1585)
        at com.amaze.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:129)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2688)
        at android.app.ActivityThread.access$2100(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at android.support.v4.app.NotificationCompat$Style.createColoredBitmap(NotificationCompat.java:1893) 
        at android.support.v4.app.NotificationCompat$Style.createColoredBitmap(NotificationCompat.java:1889) 
        at android.support.v4.app.NotificationCompat$Style.applyStandardTemplate(NotificationCompat.java:1805) 
        at android.support.v4.app.NotificationCompat$DecoratedCustomViewStyle.createRemoteViews(NotificationCompat.java:3007) 
        at android.support.v4.app.NotificationCompat$DecoratedCustomViewStyle.makeContentView(NotificationCompat.java:2963) 
        at android.support.v4.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:222) 
        at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1585) 
        at com.amaze.filemanager.asynchronous.services.ExtractService.onStartCommand(ExtractService.java:129) 
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2688) 
        at android.app.ActivityThread.access$2100(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627) 
        at dalvik.system.NativeStart.main(Native Method) 
```

Some further changes necessary, so I'm putting a **do not merge** label here, until the following are fixed
* Fix crash on Android 4.4
* Fix unit tests which should fail

However, please do take a look at the implementation first.

### CODE REVIEW

**Comment by TranceLove** [comment]
With ecfbe80 PR can be run on GPD XD running LegacyRom (4.4.4) too now; also tried on Samsung Galaxy S2 (i9100) running SlimLP (5.1.1).

Removing **do not merge** tag.

**Comment by VishalNehra** [comment]
Too many things to test, that's why taking so long. 
Anyways, everything seems fine for now. One thing I noticed, you start the service in case of a password archive while still asking for a password. IF the password is wrong, the service notification stays there. The service implementation is very delicate so it can't handle such things. 
Please start the service after a user has entered correct password. @TranceLove

**Comment by TranceLove** [comment]
This would imply trying to extract a file (even the file won't be actually written to storage) since we only know the archive is password protected when we actually extract the archive - seems the libraries we used doesn't support, nor able to detect if the archive is password-protected.

But a good idea anyway. Will look into it.

**Comment by VishalNehra** [comment]
@TranceLove I understand, in that case, lemme rephrase my statement.
Once password is entered, check if it's wrong, then cancel the extract service using the ````Intent#TAG_BROADCAST_EXTRACT_CANCEL```` broadcast.

**Comment by TranceLove** [comment]
Very sorry for the blackout for the whole May... been pinned to my day time work, and in fact, did spent quite some time on finding out the solution of stopping `ExtractService` successfully from the `AsyncTask` inside.

Tested 7261fa5 on Oneplus Two running Slim7 (7.1.2), GPD XD running LegacyROM (4.4.4), and rooted LG Nexus 5x running AOSPExtended (9.0), ExtractService and corresponding Notification can be successfully stopped after cancelling the archive password dialog.

**Comment by TranceLove** [comment]
Paths with Unicode chars... will check.

**Comment by TranceLove** [comment]
For 

> Decompressing both of these: [compress.tar.xz, compress.7z](https://github.com/TeamAmaze/AmazeFileManager/files/3325305/compress.zip) seems to be broken.

For xz file, idiot me. See ba527be.
For 7z file, unfortunately the same problem also exist when test with my workstation's JVM (OpenJDK 8 on x86_64, Ubuntu Bionic), so I think we may have to accept this for the time being, until we solve it at xz library's level.

I know there is a JNI-based implementation of LZMA from 7zip, but this is also the reason why I'd want to stay away from it.

**Comment by VishalNehra** [comment]
@TranceLove please fix conflicts so that I can do a final test before approval.

**Comment by EmmanuelMess** [comment]
> For 7z file, unfortunately the same problem also exist when test with my workstation's JVM (OpenJDK 8 on x86_64, Ubuntu Bionic), so I think we may have to accept this for the time being, until we solve it at xz library's level.

What problem would it be exactly?

> I know there is a JNI-based implementation of LZMA from 7zip, but this is also the reason why I'd want to stay away from it.

Isn't there a library that already has implemented it?

**Comment by TranceLove** [comment]
> What problem would it be exactly?

Logcat said
```
    org.tukaani.xz.CorruptedInputException: Compressed data is corrupt
        at org.tukaani.xz.LZMAInputStream.read(Unknown Source)
        at org.apache.commons.compress.utils.ChecksumVerifyingInputStream.read(ChecksumVerifyingInputStream.java:85)
        at java.io.DataInputStream.readFully(DataInputStream.java:198)
        at java.io.DataInputStream.readFully(DataInputStream.java:172)
        at com.amaze.filemanager.filesystem.compressed.sevenz.SevenZFile.readEncodedHeader(SevenZFile.java:444)
        at com.amaze.filemanager.filesystem.compressed.sevenz.SevenZFile.readHeaders(SevenZFile.java:353)
        at com.amaze.filemanager.filesystem.compressed.sevenz.SevenZFile.<init>(SevenZFile.java:239)
        at com.amaze.filemanager.filesystem.compressed.sevenz.SevenZFile.<init>(SevenZFile.java:106)
        at com.amaze.filemanager.filesystem.compressed.sevenz.SevenZFile.<init>(SevenZFile.java:260)
        at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.SevenZipExtractor.extractWithFilter(SevenZipExtractor.java:50)
        at com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractEverything(Extractor.java:73)
        at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:300)
        at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:215)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

> Isn't there a library that already has implemented it?

If you're talking about commons-compress, yes we are using it. It has a dependency, [XZ for Java](https://tukaani.org/xz/java.html), and that's the problem we are having now.

Alternately we have [7-Zip-JBinding](http://sevenzipjbind.sourceforge.net/), but it involves C++, which I wish I never need to use it.

**Comment by EmmanuelMess** [comment]
I am assuming 7zip also gives that stack trace.

For 7zip compressed data may very well be corrupt, as the file was created with Ubuntu's compression algo.

Will recheck tomorrow, along with the rest of the compressions.

**Comment by TranceLove** [comment]
> Something important is that the error should not ask for a password, it should show some kind of error state or collapse silently (the last option would be temporary).

See if fcc3d3a can help, that extracting `compress.7z` will give that "archive may be damaged or came from malicious source" toast.

Also added test cases for both `compress.7z` and `compress.tar.xz`.

**Comment by EmmanuelMess** [comment]
> See if fcc3d3a can help, that extracting compress.7z will give that "archive may be damaged or came from malicious source" toast.

Nope, just an empty folder (as if the 7zip was empty). And back button exits the app.

**Comment by TranceLove** [comment]
> > See if [fcc3d3a](https://github.com/TeamAmaze/AmazeFileManager/commit/fcc3d3a52ab920eb5c2748a2cea17a841e17caac) can help, that extracting compress.7z will give that "archive may be damaged or came from malicious source" toast.
> 
> Nope, just an empty folder (as if the 7zip was empty). And back button exits the app.

Ah, right, same goes to the test case. Will see what I can do.

**Comment by EmmanuelMess** [comment]
Tested everything again. 
What works:
* 7zip files compressed by Igor's utility work.
* tar.xz compressed by Ubuntu 18.04 works. 
* tar.lzma compressed by Ubuntu 18.04 works. 
* Compressed and encrypted zip files works.

What doesn't:
* 7zip is empty when compressed by Ubuntu 18.04.
* Encrypted 7zip breaks when decrypting files inside.


--------

[compression testing.zip](https://github.com/TeamAmaze/AmazeFileManager/files/3335039/compression.testing.zip)
7zip not encrypted: ```7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on```
7zip encrypted: ```7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -p{hi}```
Zip encripted: ```zip -e -r compress ./compress``` (pass 'hi')

------

Note when decompressing encrypted zip the first time got:

```
2019-06-27 11:02:09.900 1681-1701/system_process E/memtrack: Couldn't load memtrack module
2019-06-27 11:02:12.957 5480-5670/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: service_progress_watcher
    Process: com.amaze.filemanager.debug, PID: 5480
    java.lang.IllegalStateException: This is the first datapoint!
        at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.addDatapoint(AbstractProgressiveService.java:185)
        at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.publishResults(AbstractProgressiveService.java:162)
        at com.amaze.filemanager.asynchronous.services.ExtractService.lambda$onStartCommand$0$ExtractService(ExtractService.java:143)
        at com.amaze.filemanager.asynchronous.services.ExtractService$$Lambda$0.onProgressed(Unknown Source:26)
        at com.amaze.filemanager.utils.ProgressHandler.addWrittenLength(ProgressHandler.java:76)
        at com.amaze.filemanager.utils.ServiceWatcherUtil$1.run(ServiceWatcherUtil.java:126)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by TranceLove** [comment]
> And back button exits the app.

It seems to be the current behaviour. Before getting a crack on this issue shall we accept the current behaviour and put this into a new issue?

With ae86fe3 added toast to indicate archive corrupted when attempt to browse them. Will be exiting the app (in sync with current behaviour) in such case.

**Comment by EmmanuelMess** [comment]
> With 9968f32 added toast to indicate archive corrupted when attempt to browse them. 

None of the files tested are corrupted (unless there's a bug in Igor's compressing utility for Ubuntu).

> > And back button exits the app.
>
> It seems to be the current behaviour. Before getting a crack on this issue shall we accept the current behaviour and put this into a new issue?

Yeah, we should.

**Comment by TranceLove** [comment]
> None of the files tested are corrupted (unless there's a bug in Igor's compressing utility for Ubuntu).

OK, correct the wordings - "corrupted or just because the archiver libs we use cannot read the archive".

**Comment by EmmanuelMess** [comment]
Ok, to state my position:
Please use `cannot_extract_archive` when the archive is broken and `multiple_invalid_archive_entries` only when the "escaping the compressed file" vulnerability is used.

**Comment by zent-co** [comment]
Tested on my Nexus 5x running LineageOS (8.1.0) and on Samsung S8+ (Android Verison 9). I noticed a couple things, but I'm not sure if what I saw was expected behavior. 

I created various zips in 7zip with the xz file extension. When I moved these to each phone, I didn't see a extract option for these files. Is that expected?

Also, when extracting large (5GB) zipped files (.7zip and password protected .7zip) the extraction stalled around 700MB and created other issues, like when I tried to delete files or directories I could not. Not sure if I can extract files this large with .7z extension, but .zip extension did work for 5GB file.

**Comment by EmmanuelMess** [comment]
> I created various zips in 7zip with the xz file extension. When I moved these to each phone, I didn't see a extract option for these files. Is that expected?

I think that is an issue in master. Can you check?

**Comment by zent-co** [comment]
> @zent-co I think that is an issue in master. Can you check?

I'm confused by what I am looking for. Doesn't this PR add xz unzip support? Wouldn't that mean this wouldn't work in master either?

Either way, I didn't see an option to extract .xz files in this branch or master. Am I looking at this incorrectly?

**Comment by EmmanuelMess** [comment]
> Either way, I didn't see an option to extract .xz files in this branch or master. Am I looking at this incorrectly?

Does extract appear for zips in master? I think extract dialog is not touched by this PR, and thus if it's broken it is not a mistake in this PR.

**Comment by zent-co** [comment]
> @zent-co Does extract appear for zips in master? I think extract dialog is not touched by this PR, and thus if it's broken it is not a mistake in this PR.

Oh yes, the extract did appear for .zips in master and in this update. I didn't have any issues with .zip files in my testing.

**Comment by EmmanuelMess** [comment]
> Oh yes, the extract did appear for .zips in master and in this update. I didn't have any issues with .zip files in my testing.

Ah ok, I was wrong then, the problem was created by this PR. @TranceLove please fix.

**Comment by EmmanuelMess** [comment]
Ok, found the issue, in `FileUtils.isSelfDefault()`, "com.amaze.filemanager" should be "com.amaze.filemanager.debug"

**Comment by zent-co** [comment]
> Also, can confirm master also has the issue, @zent-co.

Maybe I'm confused about what I'm testing here. I see an extract option for .zip files, but still don't see an extract option for .xa or .7z files. Is this expected?

**Comment by EmmanuelMess** [comment]
>  I see an extract option for .zip files

Hmm, are you building the debug build or the release build?

**Comment by zent-co** [comment]
> @zent-co Hmm, are you building the debug build or the release build?

I'm building from the fix-extractdialog branch on your repository. Was building to the default build variant of fdroidDebug; tried playDebug build variant and get the same results. Should I send you a video of what I am seeing? I'm wondering if I don't know what I am looking for.

**Comment by EmmanuelMess** [comment]
> Should I send you a video of what I am seeing? I'm wondering if I don't know what I am looking for.

Yeah, maybe we are talking about different dialogs without noticing.

**Comment by EmmanuelMess** [comment]
@zent-co fix-extractdialog fixes the extract dialog for zip when using debug versions, but doesn't have TranceLove's changes that allow for extracting 7z.   
But, you said that zip extraction dialog was working for you on master, so I thought you were building not debug, but release, that's why I recommended switch to test if it was broken on master and here in this PR.  
If you are building debug, and are seeing the extraction dialog for zips either in this PR or in master, maybe we are seeing different issues or different dialogs.

**Comment by zent-co** [comment]
Attached is the .xz file (in a zip) that doesn't show an extract option on both my phone and emulator. I used 7zip to create it. Could that be an issue?

[HAL_MAL_Web.pdf.zip](https://github.com/TeamAmaze/AmazeFileManager/files/3553564/HAL_MAL_Web.pdf.zip)

**Comment by EmmanuelMess** [comment]
> Attached is the .xz file (in a zip) that doesn't show an extract option on both my phone and emulator. I used 7zip to create it. Could that be an issue?
> 
> [HAL_MAL_Web.pdf.zip](https://github.com/TeamAmaze/AmazeFileManager/files/3553564/HAL_MAL_Web.pdf.zip)

Yes, here is the stack trace:

> 2019-08-29 07:44:35.531 9639-9639/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.amaze.filemanager.debug, PID: 9639
>     java.lang.NullPointerException: Attempt to invoke virtual method 'com.amaze.filemanager.asynchronous.asynctasks.compress.CompressedHelperTask com.amaze.filemanager.filesystem.compressed.showcontents.Decompressor.changePath(java.lang.String, boolean, com.amaze.filemanager.utils.OnAsyncTaskFinished)' on a null object reference
>         at com.amaze.filemanager.fragments.CompressedExplorerFragment.changePath(CompressedExplorerFragment.java:409)
>         at com.amaze.filemanager.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:216)
>         at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2460)
>         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
>         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
>         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
>         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
>         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
>         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
>         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
>         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
>         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
>         at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
>         at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
>         at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
>         at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
>         at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
>         at android.app.Activity.performResume(Activity.java:7141)
>         at android.app.ActivityThread.performNewIntents(ActivityThread.java:2950)
>         at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2964)
>         at android.app.ActivityThread.-wrap14(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Pull request merged**
