### PR TITLE
 Move classes to new file_operations module

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@VishalNehra codacy doesn't like ShadowMultiDex as a class name, please remove those checks.

**Comment by EmmanuelMess** [comment]
@TranceLove Codacy doesn't like __constructor__:

```
  @Implementation

  public void __constructor__(URL url, NtlmPasswordAuthentication auth) {

    // intentionally empty

  }

```

Any ideas why? Should we remove the check from test files?

**Review by VishalNehra — DISMISSED** [review]

**Comment by EmmanuelMess** [comment]
@TranceLove pls test

**Review by TranceLove — COMMENTED** [review]
SingletonUsbOtgTest is not moved into file_operations module yet.

Otherwise it's OK to go.

**Comment by EmmanuelMess** [comment]
> SingletonUsbOtgTest is not moved into file_operations module yet.

I think there was a broken dependency for this one.

**Comment by EmmanuelMess** [comment]
Can this be merged now?

**Comment by VishalNehra** [comment]
@EmmanuelMess Wait to merge hotfix/3.5.1 to master.. then rebase 3.6 with master and merge this.

**Comment by EmmanuelMess** [comment]
@VishalNehra 3.6 can now be rebased.

**Comment by VishalNehra** [comment]
@EmmanuelMess Yea, sorry about that. Was out due to some work this weekend. Will push for changes tomorrow.

**Comment by EmmanuelMess** [comment]
@VishalNehra rebased.

**Review by VishalNehra — APPROVED** [review]

**Comment by EmmanuelMess** [comment]
@TranceLove please review

**Review by TranceLove — APPROVED** [review]

**Pull request merged**
