### PR TITLE
Sync translation with application functions

### PR DESCRIPTION
**Pull request by userkilled**
#### Issue tracker   

Fixes #

#### Automatic tests

- [ ] Added test cases

There was a successful assembly, I can not provide results. (I even had to edit, otherwise I was not going to)))
  
#### Manual tests
- [+] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

I can’t quite understand the last line.
 But to be honest, I'm tired of seeing another text in the application.

The translation is not perfect and needs to be further developed. I will be glad of help.

### CODE REVIEW

**Comment by userkilled** [comment]
If the time is normal, then I will try to sort the text normally in the form of :
The basis
             What does it mean
                                   Menu section
                                                               What does it mean and so on

**Comment by VishnuSanal** [comment]
hi @userkilled, thanks for your work. it's actually cumbersome to do manually add/update translations. we use [Transfeix](https://www.transifex.com/amaze/amaze-file-manager/) for translations. I'll discuss with the team on how to merge this PR. if you wish to contribute with further translations, please do so via Transfeix. thanks!

**Comment by userkilled** [comment]
With my hands it was just more visible and I did not know that you can use some software, but you need to register in it. 😑

It was a pleasant experience to be honest

**Comment by userkilled** [comment]
I tried to see what is still missing in the translation.
Something is known about the introduction of translation?

**Comment by VishalNehra** [comment]
Thanks for working! I've incorporated few of the translations on transifex, most of these were already translated. Please navigate to [transifex here](https://app.transifex.com/amaze/amaze-file-manager/translate/#ru/strings-xml--master/94508854) to translate the remaining ones :) 
Closing for now.

**Pull request closed without merging**
