### PR TITLE
Relaxing restrictions on Operations.isFileNameValid()

### LINKED ISSUE #925: Recursive copy from smb
Trying to copy a folder from a smb-location which contains other folders (lets name them child folders) would only create the child folders at the target location but ignore the contents of the child folders. 

It would be nice to be able to do recursive copies. 

Amaze version; 3.2.1

Best regards.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #925.

Also added test case for verification.

Additionally,
- migrated usage of `HybridFile.getName()` to use `HybridFile.getName(Context)` where possible
- partial fixes to test cases to make `OperationsTest` run (compared to the bigger PR #1831)

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
I need to test this yet.

**Comment by VishalNehra** [comment]
Can you please rebase this @TranceLove 
Ping @bowiechen for review

**Comment by VishalNehra** [comment]
@TranceLove I probably missed to understand how trimming `/` can fix the SMB issue of recursive file copy? Can you please explain?

**Comment by TranceLove** [comment]
> @TranceLove I probably missed to understand how trimming `/` can fix the SMB issue of recursive file copy? Can you please explain?

At SMB recursive copy, directories were seen having trailing slash calling `Operations.isFileNameValid()` so some extra check were added to strip the trailing/prefixing slashes.

https://github.com/TeamAmaze/AmazeFileManager/blob/755dc1db0da7b977ff9ae90c75eef46fe41a6b55/app/src/main/java/com/amaze/filemanager/filesystem/Operations.java#L564-L568

**Comment by VishalNehra** [comment]
Two approvals.. merging.

**Pull request merged**
