### PR TITLE
Fix redundant test runs

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   

Addresses #2586 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
The fix was copy-pasted from here: https://github.com/apache/airflow/commit/9c98a60cdd29f0b005bf3abdbfc42aba419fded8#diff-a6ce9b5b0a53d8dc6dbd59d40b23994c3e68a91fac73c0d7eacdf373c95476c9R52-R54, I dont know how to test this, and have no idea if it works.

**Comment by VishalNehra** [comment]
Make these changes on teamamaze repo branch as origin. Create pr, make another empty commit.. the previous build should get cancelled.

**Comment by EmmanuelMess** [comment]
> Make these changes on teamamaze repo branch as origin. Create pr, make another empty commit.. the previous build should get cancelled.

Does the branch's actions apply to the branch?

**Comment by EmmanuelMess** [comment]
> Make these changes on teamamaze repo branch as origin. Create pr, make another empty commit.. the previous build should get cancelled.

Seemed to work at #2611.

**Comment by VishalNehra** [comment]
@EmmanuelMess Great!

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
