### PR TITLE
Fix anonymous object for sorting search results in MainFragment

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   

Addresses #2864

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
Can you please create an issue for this and explain the problem statement?

**Comment by EmmanuelMess** [comment]
> Can you please create an issue for this and explain the problem statement?

Related to #896, but I am trying to make the leaked objects more explicit (those objects passed to the constructor will be retained).

**Comment by EmmanuelMess** [comment]
It also should help convert MainFragment to kotlin as it would have less actual code.

**Comment by EmmanuelMess** [comment]
Also it is converted to a Task, Tasks separate the "background" part from the "onError" and "onFinish" parts (better differentiation of where UI can be modified and where it cant and better error handling) and use tasks that interact nicely with React.

**Comment by VishalNehra** [comment]
Can you rebase here please.

**Comment by EmmanuelMess** [comment]
> Can you rebase here please.

Done

**Review by VishalNehra — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
