### PR TITLE
Bugfix/1894

### LINKED ISSUE #1894: Amaze 3.3.2 move/copy results are not reflect throught MTP immediately
I try to organize my images with Amaze. Therefore I go into the folder containing the images shot with OpenCamera, which is on my SD card "Pictures/Open Camera" and I create some folders and sort images into them.

Steps to reproduce the behaviour:
1. Go to /storage/[cardID]Pictures/OpenCamera, create a folder
2. Select some images
3. Since there is no "move" feature, click on the scissors icon
4. Enter the folder just created and click on the clipboard icon
5. Watch and see images appear every 10-20 seconds at a time
6. Go the the parent folder again and see images disappear 10-20 seconds at a time
7. Connect the phone to a PC and look into the Pictures/OpenCamera folder
8. Try to find the folder created in 1). Nowhere to be found!
9. Go into Amaze again, re-enter the folder, it is still there.
10. Look at the images cut in 3): They are gone (the expected result)
11. Check with the PC: there they are gone, too (expected). Again try to find the folder (nowhere, and that is unexpected).

Expected behaviour: Cutting and pasting should be executed immediately, not in ultra slow-motion. And folders created and populated in Amaze should be seen via USB on the card... Results of these operations should be noticeable on the storage media...

 - Device: Fairphone 2
 - OS: Fairphone Open OS 19.11.2 (Android Nougat 7.1.2)
 - Rooted: No and Yes (not necessary on FPOS)
 - Version: 3.3.2
 - SD card: Sandisk Ultra 128 GByte SDXC SDSQUAR-128G-GN6IA, the one sold as “up to 100 MB/Sec, Class 10, U1". Card is *very* fast, as can be seen via USB...

First, the speed cannot be explained. It is many orders of magnitude (!) slower as could be expected, second, it seems that cut & copy is not operated on the OS level (where no data at all would be moved, just the pointer in the file system modified) but actual data are transmitted. But even that doesn't explain this level of slowness.

Where exactly are my images now? According to the PC, the are no longer in the OpenCamera folder. But since the newly created folder is missing, the images can't be there. But Amaze still shows them,  so they must be somewhere. Does Amaze create temporary folders somewhere?

Exactly where are my images? I want to backup them to the PC...

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1894 
-or-   
Addresses #1908 

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Oneplus 6t
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
*DON'T MERGE* 
Pending manual testing from @hman2

**Comment by VishalNehra** [comment]
Manual testing done with success result. Few issues / crashes mentioned by @hman2 which doesn't relate to this issue.
This can be reviewed now.

**Comment by VishalNehra** [comment]
Ok. Will raise new issue for this one.

**Comment by TranceLove** [comment]
> Ok. Will raise new issue for this one.

See #1917

**Comment by hman2** [comment]
Checked encryption. Immediate crash. Syslog

**Pull request merged**
