### PR TITLE
Converted files to Kotlin

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Translated files to Kotlin

### CODE REVIEW

**Review by VishalNehra — DISMISSED** [review]

**Comment by TranceLove** [comment]
OK, I think both of us don't like the codacy problem report... so please `@Suppress` them.

Otherwise it's good to go.

**Comment by VishalNehra** [comment]
> OK, I think both of us don't like the codacy problem report... so please `@Suppress` them.
> 
> Otherwise it's good to go.

Should be relatively easy to fix these codacy issues.

**Comment by EmmanuelMess** [comment]
@TranceLove how is @Supress used?

**Comment by TranceLove** [comment]
@EmmanuelMess Not much trick here... Kotlin's own @Suppress, then comma separated list of rules that shall be skipped. Can see the tests I wrote for archive extractors😉

But for line width, that's another story... as code comment bracing the lines to skip line width.

https://github.com/pinterest/ktlint#how-do-i-suppress-an-error-for-a-lineblockfile

**Review by VishalNehra — APPROVED** [review]

**Review by TranceLove — APPROVED** [review]

**Pull request merged**
