### PR TITLE
ConnectionInfo improvements

### LINKED ISSUE #1347: Better SSH URI parsing with specialized class
URI parsing is now being done by `SshConnectionPool.ConnectionInfo`, and almost no malformation checking is made.

### LINKED ISSUE #2964: Windows SFTP server crash
## Issue explanation (write below this line)
Hello and thanks for the great work You have done!
I am watching the state is the app almost from the beginning and I am happy
to see such an evolution.
When testing it again today I found a problem opening files from Windows
SFTP server with public key authentication.
The report is below.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux
HUAWEI/STK-L21EEA/HWSTK-HF:10/HUAWEISTK-LX1/10.0.0.201C431:user/release-keys
10 - 29
* __Device:__ HWSTK-HF
* __Model:__ STK-LX1
* __Product:__ STK-L21EEA
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: Permission Denial: starting Intent {
act=android.intent.action.VIEW dat=http://127.0.0.1:7871/...
typ=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
cmp=pl.solidexplorer2/pl.solidexplorer.WebActivity } from
ProcessRecord{e1145f4 971:com.amaze.filemanager/u0a1796} (pid=971,
uid=11796) not exported from uid 10182
at android.os.Parcel.createException(Parcel.java:2071)
at android.os.Parcel.readException(Parcel.java:2039)
at android.os.Parcel.readException(Parcel.java:1987)
at
android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3888)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1731)
at android.app.Activity.startActivityForResult(Activity.java:5363)
at
androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
at android.app.Activity.startActivityForResult(Activity.java:5304)
at
androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
at android.app.Activity.startActivity(Activity.java:5734)
at android.app.Activity.startActivity(Activity.java:5702)
at
com.amaze.filemanager.filesystem.ssh.SshClientUtils.lambda$null$1(SshClientUtils.java:282)
at
com.amaze.filemanager.filesystem.ssh.-$$Lambda$SshClientUtils$Thr5zQtgEoTkSzyGp09scsjNVMw.run(Unknown
Source:4)
at android.os.Handler.handleCallback(Handler.java:888)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: android.os.RemoteException: Remote stack trace:
at
com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1184)
at
com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:903)
at
com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:651)
at
com.android.server.wm.HwActivityStarter.startActivity(HwActivityStarter.java:293)
at
com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1533)


```
</details>
<hr>

### LINKED ISSUE #3560: Can't open folders with plus ("+") in the name
**To Reproduce**
1. Create a folder called "a+b".
2. Tap on "a+b". Notice that Amaze tries to open "a b" instead.
3. Using the system file manager, move or create some files in the "a+b" folder.
4. Notice that Amaze still thinks "a b" contains 0 folders and 0 files.
5. Via Amaze, try to move or create some files in the "a b" folder. You'll get "Operation unsuccessful" or some other error.

**Expected behavior**
Amaze should be opening the "a+b" folder.
-----

This now has a bounty, [here](https://app.bountysource.com/issues/113047886-can-t-open-folders-with-plus-in-the-name).

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

### LINKED ISSUE #3636: Amaze does not properly handle file with "+" in the name
**Describe the bug**
Similar to #3560 but for files.

Amaze fales to open, rename, delete, or display properties for a file with a plus "+" in the name.

**To Reproduce**
1. Use a terminal (or other app) to create a file named `file+name.txt` and put something in it (non empty file)
2. Try open the file from Amaze - associated app closes immediately
3. Check the file properties in Amaze - 0 file size, no md5 etc
5. Try rename the file in Amaze - not renamed, or a folder is created with the new name
6. Try delete the file in Amaze - file not deleted

**Expected behavior**
All actions work as expected - open file, rename file, see file size

**Smartphone**
 - Nokia 6.1, Lineage OS, Amaze 3.8.2 (Fdroid)
 - Sony Xperia XA, lastest Amaze from Play Store

**Additional context**
Discovered after downloading a file from the web with a name like `Something+foo+-+bar.pdf`
Can do more testing if needed.

### LINKED ISSUE #3739: Going back in SFTP connection leaves trailing slash
**Describe the bug**
If you are in a directory, and go back to the parent directory, it leaves a trailing slash. Going back and forth between a parent and a child builds up a series of forward slashes. There is also an issue that seems to be related which results in "No files" being shown.

**To Reproduce**
1. Connect to a SFTP server
2. Navigate to some directory
3. Go back to parent
4. See trailing slash
5. Tap on (any) child directory
6. See two slashes between parent and child

**Expected behavior**
When going back, the trailing slash should be removed

**Screenshots**
This screenshot also shows the "No files" issue. I navigated between "Downloads" and "rusefi" a number of times before it stopped showing the files.
Screenshot_20230218-173801_Amaze

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T
 - OS: LineageOS 20
 - Rooted: No
 - Version: 3.8.5

### PR DESCRIPTION
**Pull request by TranceLove**
## Description
To tackle problems with FTP/FTPS/SSH URLs having complex characters, and over-complicated parsing logic in ConnectionInfo.

URL format is
`<scheme>://<base64-encoded username>:<encrypted base64-encoded password>@<host>:<port><path, if specified>`

And because of the changes in URL format, there will be incompatibilities with FTP/FTPS/SSH URLs currently stored in database. You will have to create them again...

Changes:
- Decouple ConnectionInfo from NetCopyClientConnectionPool to individual class
- Use proven regex to parse URI instead of mangling substrings all the time. `Uri.parse()` is not working for our URLs here, hence had to use yet another ways
- Defer decrypting password until authentication callables

#### Issue tracker   
Fixes #1347, fixes #2964, fixes #3636, fixes #3560, fixes #3739

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by TranceLove** [comment]
TODO:

- [ ] More testcases, covering query string and even more complicated URLs
- [ ] Manual tests with true FTP/FTPS/SSH connections

**Comment by TranceLove** [comment]
Added handling of path names containing plus sign (+) in c73cf51. Hope this can fix #3636 and #3560 as well.

**Comment by VishalNehra** [comment]
So initial loading seem to work on smb, however after I close and restart the app, and tap the connection again, it's not able to load the list.

```
023-01-30 01:49:33.713 25283-29073 c.a.f.a.a....esListTask com.amaze.filemanager.debug          W  [AsyncTask #4        ] Failed to load smb files for path: smb://demo:Abc@42353@192.168.0.102/jcifs.smb.SmbException: NTLMv2 requires extended security (jcifs.smb.client.useExtendedSecurity must be true if jcifs.smb.lmCompatibility >= 3)
                                                                                                    	at jcifs.smb.NtlmPasswordAuthenticator.getSigningKey(NtlmPasswordAuthenticator.java:519)
                                                                                                    	at jcifs.smb.SmbSessionImpl.sessionSetupSMB1(SmbSessionImpl.java:890)
                                                                                                    	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:486)
                                                                                                    	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
                                                                                                    	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
                                                                                                    	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
                                                                                                    	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614)
                                                                                                    	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568)
                                                                                                    	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
                                                                                                    	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
                                                                                                    	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
                                                                                                    	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
                                                                                                    	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:201)
                                                                                                    	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
                                                                                                    	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1213)
                                                                                                    	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listSmb(LoadFilesListTask.java:599)
                                                                                                    	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:154)
                                                                                                    	at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-01-30 01:49:33.739 25283-25283 c.a.f.u.f.MainFragment  com.amaze.filemanager.debug          W  [main                ] Load list operation cancelled
```

**Comment by VishalNehra** [comment]
This is still in WIP?

**Comment by TranceLove** [comment]
> This is still in WIP?

Still a few rough edges after countless nights struggling a problem writing loops using `Flowable.fromIterable()` with nullable results...

- [ ] Fix Codacy complaints
- [ ] Fix update SSH connection problems, cannot delete connection
- [ ] Actual tests again
- [ ] Code cleanup - want to remove `HybridFileExt`

**Comment by TranceLove** [comment]
After 8d0654c #3739 should be solved. Allow me a couple of nights more to finish the remaining tasks...

**Review by VishalNehra — APPROVED** [review]

**Comment by seemebreakthis** [comment]
👏👏 Hopefully it will be released soon.  Or I have any way of downloading the pre-release version?

**Pull request merged**
