### PR TITLE
Feature add pCloud

### PR DESCRIPTION
**Pull request by VishalNehra**
Adds support for pCloud 
Ps. requires new changes in Amaze cloud plugin to test. I've sent over the apk file via email.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
I recommend not pulling this PR until 3.3.0 has been released so that there are less last minute bugs.

**Comment by VishalNehra** [comment]
This doesn't introduce any new code, just an extension of API.

**Comment by EmmanuelMess** [comment]
500 addittions…

**Comment by TranceLove** [comment]
Quick test, on Oneplus One running Slim7 2.0 stable (7.1.2) and locale set to Japanese

- create directory OK
- rename directory OK
- unable to delete directory
- unable to create file on pCloud
- unable to copy file to nor download file from pCloud

When I attempt to download file from pCloud or delete directory, app crashed with exception

```
03-12 23:03:02.078  2782  2869 W System.err: java.text.ParseException: Unparseable date: "Thu, 08 Mar 2018 11:45:38 +0000"
03-12 23:03:02.091  2782  2869 W System.err: 	at java.text.DateFormat.parse(DateFormat.java:358)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.cloudrail.si.types.Date.<init>(Date.java:48)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.cloudrail.si.servicecode.commands.Create.execute(Create.java:138)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.cloudrail.si.services.PCloud.getMetadata(PCloud.java:1025)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:556)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.amaze.filemanager.utils.files.FileUtils.getBaseFileSize(FileUtils.java:209)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.amaze.filemanager.utils.files.FileUtils.getTotalBytes(FileUtils.java:203)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.doInBackground(PrepareCopyTask.java:108)
03-12 23:03:02.092  2782  2869 W System.err: 	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.doInBackground(PrepareCopyTask.java:46)
03-12 23:03:02.092  2782  2869 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-12 23:03:02.092  2782  2869 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
03-12 23:03:02.098  2782  2869 E AndroidRuntime: Process: com.amaze.filemanager, PID: 2782
03-12 23:03:02.098  2782  2869 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: Caused by: java.lang.RuntimeException: ServiceCode Error in function extractMetaData at 8: set $P1.modifiedAt $L0.time 
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:127)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.services.PCloud.getMetadata(PCloud.java:1025)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.amaze.filemanager.filesystem.HybridFile.isDirectory(HybridFile.java:556)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.amaze.filemanager.utils.files.FileUtils.getBaseFileSize(FileUtils.java:209)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.amaze.filemanager.utils.files.FileUtils.getTotalBytes(FileUtils.java:203)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.doInBackground(PrepareCopyTask.java:108)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.doInBackground(PrepareCopyTask.java:46)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	... 3 more
03-12 23:03:02.098  2782  2869 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.types.SandboxObject.get(SandboxObject.java:32)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Sandbox.getEntry(Sandbox.java:231)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:282)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:249)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.commands.Set.execute(Set.java:35)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
03-12 23:03:02.098  2782  2869 E AndroidRuntime: 	... 12 more
```

The same `java.text.ParseException` also occurred when I tried to create file on pCloud, but app didn't crash.

Not sure I'll want to poke into CloudRail's library to look into the details, but if it worked for you but not for me, I suppose there might be something hardcoded?

**Comment by VishalNehra** [comment]
I am also getting this error. I've created a ticket on cloudrail about this.
Can be tracked [here](https://cloudrail.freshdesk.com/public/tickets/675f2ddf6646feafad65899daff871248a5a6d1d9dadccfed255b8fcab9e41d6)

**Comment by VishalNehra** [comment]
Most bugs are fixed now, with new cloudrail release except for moving/copying file within pcloud, or uploading to pcloud.
Can't get a stack trace for these so I can't pinpoint the cause.

**Comment by VishalNehra** [comment]
@TranceLove create new file does work. It just takes some time to reflect i.e. doesn't reflect back on subsequent refresh after the operation. You can confirm by visiting their web version, or in few minutes in Amaze itself.

**Comment by TranceLove** [comment]
> @TranceLove create new file does work. It just takes some time to reflect i.e. doesn't reflect back on subsequent refresh after the operation. You can confirm by visiting their web version, or in few minutes in Amaze itself.

OK, saw it on the web now. Thanks for the tip.

**Comment by TranceLove** [comment]
With the latest changes
 * Upload file still not working
 * Download file started to work (speed is slow though; looks like pCloud's own problem since download from browser is also slow)
 * Create new file still requires some time for the file to appear

Overall, it's still a pain to see some file operations take longer time than I'd expect...

**Comment by EmmanuelMess** [comment]
This is way too old. Closing.

**Pull request closed without merging**
