### PR TITLE
Drawer width should follow design guidelines #1119

### LINKED ISSUE #1119: Drawer width should follow design guidelines
> Side nav width: Equal to the screen width minus the height of the action bar. In the example shown above, the nav drawer is 56dp from the right edge of the screen.
>
> Maximum width: The maximum width of the nav drawer is 280dp on mobile and 320dp on tablet. This is calculated by multiplying the standard increment by five (the standard increment is 56dp on mobile and 64dp on tablet).

Source: [Patterns – Navigation drawer](https://material.io/guidelines/patterns/navigation-drawer.html#).

This app [just makes the drawer width be 304dp](https://github.com/TeamAmaze/AmazeFileManager/blob/eeba4b5ee45aa721ece6770991d94453db6b2b54/app/src/main/res/values/dimens.xml#L5).

### PR DESCRIPTION
**Pull request by michaelsam94**
Fix #1119

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
A lot of the lines you added are consecutive blank lines. It isn't the end of the world, but try not to do it...

**Comment by EmmanuelMess** [comment]
Also, you made changes to other code that doesn't go towards the goal of this PR ("Fix #1119"), and makes it more difficult to find the code that does.

**Comment by michaelsam94** [comment]
I use default formatter in android studio are ctrl+shift+L is there another formatter you use here I will try next time to minimize changes that require change in others code but i need to know what is device you test on thanks

**Comment by EmmanuelMess** [comment]
Nexus one with API 27.

**Comment by michaelsam94** [comment]
I try on nexus one but there is no problem in space 
nexus_one

**Comment by michaelsam94** [comment]
the is 3 commits in this PR maybe you checkout the first commit only

**Pull request closed without merging**
