### PR TITLE
Add support for password-protected RARs

### LINKED ISSUE #2099: Support password-protected RAR archives
After #2096 merged password-protected RAR archives can be supported.

### LINKED ISSUE #2274: Crash on RarExtractor::extractWithFilter : Extracting 0 files
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux
realme/RMX1992/RMX1992L1:10/QKQ1.191201.002/1602732340:user/release-keys 10
- 29
* __Device:__ RMX1992L1
* __Model:__ RMX1992
* __Product:__ RMX1992
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing
doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at
com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.RarExtractor.extractWithFilter(RarExtractor.java:73)
at
com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractEverything(Extractor.java:77)
at
com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:315)
at
com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:225)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TranceLove**
Additionally, converted corresponding test cases to Kotlin.

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2099
Fixes #2274

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Fairphone 3
- OS: LineageOS 16.0 (9.0)

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Okay, if I try to extract a v5 it tells me that v5 isn't supported, but if I try to view it, a toast tells me it is broken.

**Comment by EmmanuelMess** [comment]
It also seems to take quite a bit of time to test passwords, and when you put an incorrect password it just says "Error". Also, it allows you to extract from the rar with an incorrect password.

**Comment by TranceLove** [comment]
> It also seems to take quite a bit of time to test passwords, and when you put an incorrect password it just says "Error". Also, it allows you to extract from the rar with an incorrect password.

At current state of junrar, we cannot know if user had entered wrong password until checking extracted file's checksums - the same as they do.

https://github.com/junrar/junrar/blob/bac58479ad4731a31363e8626f167e9a2d84daac/src/main/java/com/github/junrar/Archive.java#L585-L592

**Comment by EmmanuelMess** [comment]
> At current state of junrar, we cannot know if user had entered wrong password until checking extracted file's checksums - the same as they do.

Can't we extract the fastest _thing_ possible first, to check the password? If a rar is 300MB but contains a 3MB file, test the password with that, not the whole rar.

**Comment by TranceLove** [comment]
Implemented method to find and try extract the smallest entry in the RAR.

> when you put an incorrect password it just says "Error"

With the current state of junrar, how would you distinguish a true file checksum error due to corrupt archive, and a file checksum error caused by incorrect archive password?

**Comment by EmmanuelMess** [comment]
> With the current state of junrar, how would you distinguish a true file checksum error due to corrupt archive, and a file checksum error caused by incorrect archive password?

Ok, corrupt header exception seems to be the preferred exception to check password correctness, as it is more probable that the header was uncorrected unencrypted and less probable that the header has been corrupted.

**Comment by EmmanuelMess** [comment]
Ran this to get the error:
```java
        @Test
        public void givenEncryptedRar4File_whenCreatingArchiveWithPassword_thenItCanExtractContent() throws Exception {
            try (InputStream is = getClass().getResourceAsStream("password/rar4-encrypted-junrar.rar")) {

                try (Archive archive = new Archive(is, "jun")) {
                    archive.getFileHeaders().get(0).getFileCRC();
                }
            }
        }

```
With [rar4-encrypted-junrar.rar.zip](https://github.com/TeamAmaze/AmazeFileManager/files/5897424/rar4-encrypted-junrar.zip)

**Comment by TranceLove** [comment]
> Ran this to get the exception:
> 
> ```java
>         @Test
>         public void givenEncryptedRar4File_whenCreatingArchiveWithPassword_thenItCanExtractContent() throws Exception {
>             try (InputStream is = getClass().getResourceAsStream("password/rar4-encrypted-junrar.rar")) {
> 
>                 try (Archive archive = new Archive(is, "jun")) {//Exception gets thrown on this line
>                     archive.getFileHeaders().get(0).getFileCRC();
>                 }
>             }
>         }
> ```
> 
> With [rar4-encrypted-junrar.rar.zip](https://github.com/TeamAmaze/AmazeFileManager/files/5897424/rar4-encrypted-junrar.zip)
> 
> It seems that exception only gets thrown in one line of code in junrar: Archive.java:324

Couldn't even open using `rar` installed on my workstation... perhaps can only helpful to handle reading corrupt RAR archives.

**Comment by EmmanuelMess** [comment]
The rar file is from the junrar project test resources. I don't think it is broken, as it is opened in a test and read.

**Comment by VishalNehra** [comment]
Can't seem to extract `test-archive-sizes.rar` in this PR with password `123456` 🤔

**Comment by TranceLove** [comment]
> Can't seem to extract `test-archive-sizes.rar` in this PR with password `123456` thinking

How did it happen? Seems the unit tests are passing...

**Comment by EmmanuelMess** [comment]
Potential vulnerability, extracting twice the password doesn't have to be reentered.

**Comment by EmmanuelMess** [comment]
Trying to extract with the wrong password prompts the dialog again, but doesn't say that the password was wrong.

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
* Password is remembered for a file with a name (for files with the same name it doesn't ask for password).
* Trying to extract with the wrong password prompts the dialog again, but doesn't say that the password was wrong.

**Review by EmmanuelMess — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
