### PR TITLE
Add package name to App Manager

### LINKED ISSUE #3780: Show package name in app manager
**Is your feature request related to a problem? Please describe.**
It would be nice to see the package name since properties just open settings of the app.

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes #3780

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by TranceLove** [comment]
@VishnuSanal Sometimes when I come back from other app when I'm in app manager the package names will disappear.

Steps to reproduce:
1. Open App Manager
2. The apps and package names are there
3. Open an app from App Manager
4. Mangle around
5. Exit app opened in 3, go back to App Manager
6. App list is there but without package names

Fairphone 3 running LineageOS 19.1 (Android 12).

**Comment by VishnuSanal** [comment]
@TranceLove can't reproduce :( When I come back from another app, the package names are visible & the list just jumps to the top. I tested on an Android 12 emulator, Android 13 emulator & my daily driver (A11). Maybe, the TextView got hidden since its visibility is set to GONE by default (and it didn't get set to VISIBLE from `AppHolder#init` when AppManager was opened again)? 🤔

**Comment by TranceLove** [comment]
> @TranceLove can't reproduce :( When I come back from another app, the package names are visible & the list just jumps to the top. I tested on an Android 12 emulator, Android 13 emulator & my daily driver (A11). Maybe, the TextView got hidden since its visibility is set to GONE by default (and it didn't get set to VISIBLE from `AppHolder#init` when AppManager was opened again)? :thinking: 

I tried clean build once more from my Fairphone 3 again, seems I couldn't reproduce it either. Also tried again with Pixel 6 emulator running Android 13, same result.

I'd consider previous comment as false alarm.

**Review by TranceLove — DISMISSED** [review]

**Review by VishalNehra — CHANGES_REQUESTED** [review]
Required changes in UI as per discussion

**Review by VishalNehra — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
