### PR TITLE
SDK 33 adaptations, language and library upgrades

### PR DESCRIPTION
**Pull request by TranceLove**
## Description

- Compile using SDK 33
- Use Kotlin 1.8
- Use Java 11
- Adaptations to fix errors brought by upgrade
  - Default to Light theme if `AppTheme` returns `SYSTEM`
  - `HasherOfMenuItem.title` is `CharSequence?` as SDK 33 marked
  
#### Manual tests
- [ ] Done  
  
#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by TranceLove** [comment]
@VishalNehra Probably related: https://stackoverflow.com/questions/74201274/changed-targetsdkversion-to-33-from-30-and-now-notifications-are-not-coming-up

**Comment by VishalNehra** [comment]
Not able to grant storage access permissions using existing implementation. No storage permissions getting shown on system settings > apps > amaze as well. What did Google do.

**Comment by TranceLove** [comment]
Pending tasks:

- [ ] Fix notification permission request
- [ ] Fix storage permission request
- [ ] Fix the below warning (optional, not showstopper)

```
'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
By default will become an error since Gradle 8.0+! Read more: https://kotl.in/gradle/jvm/target-validation
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

**Comment by VishalNehra** [comment]
@TranceLove I've made small changes, from what I've tested, it seem to be working, we might need to test on few more android 13 devices. Although it still doesn't show storage permission in system settings any more (google seem to have removed it altogether), we're able to read / write files just fine.

**Comment by TranceLove** [comment]
Thanks @VishalNehra that seems to have fixed the problems we had. I also added the use of `jvmToolchain` to workaround the Kotlin compilation tasks' warnings.

Tested on Fairphone 3 running LineageOS 20 (13), so far so good.

Pending tasks:
- [ ] Test on Android 4.4
- [ ] Test on Android 9/10
- [ ] Test on Android 11/12

**Comment by VishalNehra** [comment]
Merging this as required urgently.

**Comment by VishnuSanal** [comment]
> Merging this as required urgently.

probably @TranceLove should give his verdict too

**Pull request merged**
