### PR TITLE
Add iw string res

### PR DESCRIPTION
**Pull request by davidHarush**

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
`paddingRight`? why not `paddingStart`?

**Comment by davidHarush** [comment]
I added `android:paddingRight` to a few LinearLayouts, 
If you look at their children you will see that is no paddingRight only paddingLeft
```xml
           <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical"
                    android:paddingBottom="@dimen/material_generic"
                    android:paddingRight="@dimen/material_generic"
                    >

                    <!-- title -->
                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/material_generic_large"
                        android:paddingLeft="@dimen/material_generic"
                        >
                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_centerVertical="true"
                            android:text="@string/translators"
                            android:textColor="@android:color/darker_gray"
                            />
                    </RelativeLayout>
           .
           .
           .
          </LinearLayout>
```
I preferred to do it only to the parent view end not for all his children.

Form my experience (Hebrew speaker mother name) rtl layout in addition to lrt layout is not needed but but I agree that in more effective way.

If you want I can try to edit and improve the this layout..

**Comment by EmmanuelMess** [comment]
> rtl layout in addition to lrt layout is not needed

If you find a readable and easily understandable way of making the single layout work both ways, the change is welcome, but I couldn't find such a way.

**Comment by davidHarush** [comment]
> > rtl layout in addition to lrt layout is not needed
> 
> If you find a readable and easily understandable way of making the single layout work both ways, the change is welcome, but I couldn't find such a way.

OK, i will delete the layout commits, continue to translate and will refactor the layout when I have more time to do it right (maybe even in a new branch).

**Comment by davidHarush** [comment]
> > rtl layout in addition to lrt layout is not needed
> 
> If you find a readable and easily understandable way of making the single layout work both ways, the change is welcome, but I couldn't find such a way.

OK, i will delete the layout commits, continue to translate and will refactor the layout when I have more time to do it right (maybe even in a new branch).

**Comment by EmmanuelMess** [comment]
Two approvals, merging.

**Pull request merged**
