### PR TITLE
Fixed going back on back icon click

### LINKED ISSUE #1041: Pressing compressed 'back' item on the arrow doesn't go back
Pressing compressed 'back' item on the arrow doesn't go back. It doesn't do anything.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Fixed going back on back icon click.
Fixes #1041

### CODE REVIEW

**Comment by TranceLove** [comment]
Can't say much on this since I wasn't able to reproduce the symptom mentioned in #1041.

Code seems OK however.

**Comment by VishalNehra** [comment]
Agree with @TranceLove

**Comment by EmmanuelMess** [comment]
To reproduce go to a compressed file, view it, and press the arrow, it should go back but it doesn't.

**Comment by TranceLove** [comment]
Verified working with Lollipop emulator. Voted +1.

**Comment by EmmanuelMess** [comment]
@VishalNehra You approved but didn't know what the bug was, what do you say now?

**Comment by TranceLove** [comment]
Maybe @VishalNehra agreed on "code seems OK" point...

I really didn't know about this feature and I won't know if others is using it or can reproduce the problem.

**Comment by EmmanuelMess** [comment]
So that everyone is in the same page: clicking inside the circle doesn't do anything
screenshot_1520004143
This is in contrast to MainFragment's back that does work. This is a bug fix, not a feature.

**Comment by VishalNehra** [comment]
Approved

**Comment by EmmanuelMess** [comment]
@TranceLove?

**Comment by TranceLove** [comment]
> @TranceLove?

Didn't I give a +1?

**Pull request merged**
