### PR TITLE
Add support for FTP server saving to external storage/SD card

### LINKED ISSUE #1008: no ftp file transfer into sdcard
Hi,
  while I am am to transfer files from android to sdcard and vice versa. I can only transfer file via ftp into the android part, but not into the sdcard!

Using a Sony Z1, Android 7 or 8 (updated in last days.)

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1008.

Included a set of filesystem integration classes specific to Android devices, based on `DocumentFile`, so file I/O will be done with ContentResolver; also cherry-picked 2 commits in #1087 for choosing FTP server's shared path with FolderChooser.

I suspect the SlimLP (5.1.1) I use on my Galaxy S2 was short-circuited that write request to micro SD card slot didn't trigger SAF popup, even with a fresh install. While change FTP server share path worked on Nougat emulator (Pixel 2) with external SD card, please help test on true devices having SD card slot and running Android >= 5.1.1, to verify the correctness of the implementation, especially uploading file to FTP server with shared path on the external SD card.

### CODE REVIEW

**Comment by VishalNehra** [comment]
I tried testing, but ````
import com.afollestad.materialdialogs.folderselector.FolderChooserDialog;```` doesn't exist so it won't compile against master.

**Comment by TranceLove** [comment]
Weird. I too got the import error, but the dependency was there...

Anyway, try with 51f800e which had rebased with master and re-imported the class.

**Comment by EmmanuelMess** [comment]
Device Moto E2 4G, Android 6
Got permission denied after trying to create a file with filezilla (on sd):
```
com.amaze.filemanager W/System.err: [pool-6-thread-1] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (192,168,0,10,216,253)
com.amaze.filemanager W/System.err: [pool-6-thread-2] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - RECEIVED: STOR t.txt
com.amaze.filemanager W/DocumentFile: Failed to createFile: java.io.IOException: open failed: EACCES (Permission denied)
com.amaze.filemanager W/System.err: [pool-6-thread-2] WARN org.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 55549
com.amaze.filemanager W/System.err: [pool-6-thread-1] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - SENT: 550 /storage/6B5C-B713/tempt.txt: Permission denied.
```

The file wansn't created after the connection was accepted and the file was (apparently) correctly transfered:
Android:
```
com.amaze.filemanager W/System.err: [pool-20-thread-6] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.
com.amaze.filemanager W/System.err: [pool-20-thread-6] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - SENT: 226 Transfer complete.
```
FileZilla:
```
Estado:	Directory listing of "/storage/emulated/0/DCIM" successful
Estado:	Comenzando la subida de /tmp/fz3temp-1/empty_file_yq744zm
Estado:	Transferencia correcta, transferidos 0 B en 1 segundo
```

Question: Why is everything sent recorded under "Warning" in the logcat? That is not a good idea, as the guidelines recommend reducing the output to logcat.
> * Configuring your application for release.
> At a minimum you need to remove Log calls 

-- [Android Developers: Publish Your App - Preparing your app for release](https://developer.android.com/studio/publish/)

**Comment by TranceLove** [comment]
OK, this looks more work should be done.

> Question: Why is everything sent recorded under "Warning" in the logcat?

Possibly I forgot to switch off logging, or I need to force Apache FtpServer to keep quiet. I'll check.

**Comment by EmmanuelMess** [comment]
Remember how internal storage file creations worked but no file was created? They were created in the parent directory as "<supposed parent folder name>fsdfs.txt". There's a separator missing somewhere I would guess.

**Comment by TranceLove** [comment]
> Remember how internal storage file creations worked but no file was created? They were created in the parent directory as "fsdfs.txt". There's a separator missing somewhere I would guess.

Indeed, must have wrongly interpreted the way they transverse the path. But allow me to resume this after I got through my own work 😓

**Comment by TranceLove** [comment]
> Question: Why is everything sent recorded under "Warning" in the logcat?

Directing [slf4j output to Android logcat](https://www.slf4j.org/android/) might help. See 4130771.

Path resolve problem is still being worked on.

**Comment by TranceLove** [comment]
As of 0f60098 I made an overhaul to the integration, and added a series of torture tests, to make sure end user is trapped below the directory set in Amaze, after inspiration of the __slip-zip__ security vulnerability.

Also borrowed 881e0e2 from #1250 for upload/download tests.

**Comment by VishalNehra** [comment]
I'm willing to get this through @TranceLove ? Please rebase with release/3.5 :)

**Comment by TranceLove** [comment]
This PR needs deprecation due to the huge gap with the release/3.5 branch, as well as old APIs being used.

**Pull request closed without merging**
