### PR TITLE
Merge release/3.7 to master

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by EmmanuelMess — DISMISSED** [review]
lots of changes :P

**Comment by VishalNehra** [comment]
@TranceLove can you look at the failing emulator test please

**Comment by TranceLove** [comment]
@VishalNehra Please merge #3284 and try this again.

**Comment by VishalNehra** [comment]
@TranceLove Thanks

**Pull request merged**
