### PR TITLE
#1714 Commit for dismissing contextual toolbar when swithching in and…

### PR DESCRIPTION
**Pull request by pcsaunak**
… out of focus

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build failing
Also please write in description which issue is being fixed

**Comment by pcsaunak** [comment]
Ok. Let me cross check why it's failing. I just added a line in the
mainfragment.

**Comment by pcsaunak** [comment]
> Build failing
> Also please write in description which issue is being fixed

@VishalNehra Looking at the build error here, it says error from spotless, is it just because of formatting ? Because I tested it in my local machine and it worked absolutely fine.

**Comment by VishalNehra** [comment]
Yea. Perform `./gradlewspotlessCheck` 
If any formatting errors it'll tell you to perform `./gradlewspotlessApply` and will automatically fix the formatting.

**Comment by VishalNehra** [comment]
Closing, as per discussion in #1714

**Pull request closed without merging**
