### PR TITLE
Ability to disable marquee

### PR DESCRIPTION
**Pull request by proninyaroslav**
Hi. It would be great to be able to disable marquee, for example, for me this way of displaying text isn't very informative.

### CODE REVIEW

**Comment by VishalNehra** [comment]
Personally I'm not in favor to put this option. We can increase the initial time to start marquee to something more suitable, though.

**Comment by proninyaroslav** [comment]
Well, I think everyone has a different perception of time. For someone it will be fast, but for someone it will be slow. Maybe make time options for marquee (slow, medium, fast)?

**Comment by VishalNehra** [comment]
That's just opposite of what my concern is. I don't want settings to be all cluttered up. That's why I suggest to keep the delay times which would help every one.

**Comment by proninyaroslav** [comment]
This is the same element of perception as a color theme, which can also be customized in your app. Then it makes no sense to leave ability to change a color theme if you can't customize other visual things. But this is a question of philosophy and design.

**Comment by VishalNehra** [comment]
@proninyaroslav yep, definitely it's a design perspective. I also got a few queries through mail to have the ability to disable this effect. I think we can keep this preference. Just move it from 'Interface' to 'General' in preference.

**Comment by proninyaroslav** [comment]
Done.

**Comment by VishalNehra** [comment]
@proninyaroslav Also, please change the english title to 'Enable marquee effect for file names' instead. Then all okay from my side too (:

**Comment by EmmanuelMess** [comment]
Why was this added to 3.3.1?

**Pull request merged**
