### PR TITLE
Solved: continuously showing permission not granted toast

### LINKED ISSUE #1866: Runtime permission denial for storage makes trouble
**Runtime permission denial for storage makes trouble**
After showing the permission dialog If I click `Deny & Don't Ask Again`, it continuously showing toast `Permission not granted`. If I stay on the screen for few seconds and exit from app, showing still appears on screen because Toasts could not finish showing all, while the app was open.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app for the first time or every time you click after `Deny & Don't Ask Again` 
2. After showing runtime permission dialog, click `Deny & Don't Ask Again` 
3. Stay for few seconds 
4. Exit the app manually, see that Toast is still there.

**Expected Behaviour**
An extra dialog with **Allow** & **Exit** button can be shown to the user to explain why this app needs storage permission. If the user feels comfortable with this explanation, he can press **Allow** to be directly navigated to the default runtime permission or **Deny** to exit from the app.

**Screenshots**
Amaze

**Smartphone :**
 - Device: Nokia 7 Plus
 - OS:  Android 10
 - Rooted:  No
 - Version: 3.4.3

**Additional context**
You can print the Toast message in the console log and see that it continuously prints that `Permission not granted` message as I've added on that screenshot.

### PR DESCRIPTION
**Pull request by ShivangMahajan**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1866 
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by TranceLove** [comment]
While this fixes the problem that the Toast kept on floating around the screen, I had another problem came up.

1. Launch Amaze
2. Storage permission prompt
3. Deny
4. Toast "Permission not granted"
5. Press back
6. Toast became "Press again to exit"
7. Press back again to exit app
8. Launch Amaze again
9. No file list, no storage permission prompt, only a Toast saying "Permission not granted"

Perhaps some more changes to fix this problem, so users won't need to go to app properties to grant the storage permission by hand?

Additionally, the best case scenario as reported in #1866 that Amaze should prompt the user why he/she needs to grant storage permission to Amaze.

> __Expected Behaviour__
An extra dialog with Allow & Exit button can be shown to the user to explain why this app needs storage permission. If the user feels comfortable with this explanation, he can press Allow to be directly navigated to the default runtime permission or Deny to exit from the app.

This PR doesn't implement this expected behaviour, so I don't think this will fix #1866, only addresses it instead.

Tested on Pixel 2 emulator running Android 10.

**Comment by ShivangMahajan** [comment]
I have tested this code on realme X android 10. I have not faced this issue. If the user clicks on deny then this dialog is shown to the user:
WhatsApp Image 2020-06-12 at 9 21 24 PM

If the user clicks on 'cancel', then the app is closed and if the user opens the app again then again this dialog is shown. But if the user clicks on 'grant' then this permission dialog is shown:
WhatsApp Image 2020-06-12 at 9 21 25 PM

If the user clicks on deny and don't ask again, then no dialog is shown to the user and only the permission not granted toast is shown. If the user again opens the app, then only the toast is shown.
If the user clicks on deny and don't ask again button, then the user have to go manually to the app properties to allow the permission. As he/she has selected don't ask again option, so the permission dialog can't be shown to the user again.

Maybe the problem you have mentioned occurs only in emulator.

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
@TranceLove you didn't list down the device you tested on.
From what I can see, this should be working fine.
Can you checkout PR #1906 ? I've followed difference approach there, essentially it's similar. Check if they're working fine or not.

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
Thanks for the PR @ShivangMahajan it seems while trying out fixing this issue, I already implemented some more functionality (showing a snackbar when permission is not granted by user, see #1906 ). So I'll have to close this one, as the other PR is already merged and issue is closed. 
While I acknowledge your time and effort for this work, request you to pick up some other issue if you get time (: 
Also do join our telegram channel if you want to be certain we don't pick issues that are already picked by someone else :) 
https://t.me/joinchat/NNFgWxQUB8fFE3yCsC0w4g

**Pull request closed without merging**
