### PR TITLE
Fix drawer width and Drawer class cleanup by @michaelsam94

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Fixes #1122 

Squashed #1122's commits into two and removed consecutive empty lines and `if(...) {...} else {...}` (all in the same line) constructs.

### CODE REVIEW

**Comment by michaelsam94** [comment]
Thank you @TranceLove  👍

**Comment by VishalNehra** [comment]
Why 2 PRs for same thing? Might as well close one of these.

**Comment by michaelsam94** [comment]
I pull request second time because the first pull request don't handle device orientation I need to apply width of drawer in portrait mode only because in landscape not looking good

**Comment by michaelsam94** [comment]
can I merge two pull requests?

**Comment by VishalNehra** [comment]
@michaelsam94 merged this one. Hope you wouldn't mind. Thanks for your contribution (:

**Comment by michaelsam94** [comment]
@VishalNehra sure no mind 👍

**Pull request merged**
