### PR TITLE
Preserve overwriting extraction path by service

### LINKED ISSUE #1088: Can't open files from CompressedExplorerFragment
Unable to open file from fragment, it just extracts to parent of compressed file.
Bug introduced in #837

### PR DESCRIPTION
**Pull request by VishalNehra**
Fixes #1088

### CODE REVIEW

**Comment by TranceLove** [comment]
After applying it is now possible to open a file inside the zip without extracting first that #1088 mentioned.

I'd vote a +1.

**Comment by VishalNehra** [comment]
Commit added to fix #1090

**Comment by VishalNehra** [comment]
I think user should be expecting that much. Regardless, I'm adding new changes to reflect the same.

**Comment by EmmanuelMess** [comment]
Most of our users won't know what " (r/o)" means. My recommendation, a dialog that says something like "This file can only be read, you cannot make changes".

**Comment by VishalNehra** [comment]
Let's not consider users this dumb. Save button is disabled by default and it won't be visible unless you make any change. Showing dialog to user everytime he opens a text file from compressed file would be too reduntant, user would get annoyed. Let's keep it simple.

**Comment by EmmanuelMess** [comment]
It's computational jargon, users aren't dumb, it's just that the meaning of "r/o" doesn't concern them.

**Comment by EmmanuelMess** [comment]
Maybe a Snackbar intead of dialog?

**Comment by VishalNehra** [comment]
@EmmanuelMess I agree and have made the changes suggested by you.

**Comment by EmmanuelMess** [comment]
Will test

**Comment by EmmanuelMess** [comment]
What do you think of the last commit @TranceLove ?

**Pull request merged**
