### PR TITLE
Proguard

### LINKED ISSUE #977: Update Proguard and enable it
Proguard helps maintain apk size down, but for it to work some libs have special requirements, I think CloudRAIL was one of them.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Added proguard rule for CloudRail, SpongyCastle
* Added @TranceLove 's rules for jssh
* Added proguard rules for tests (in another file)
* Removed '-dontwarn' rule and unnecessary lines in `proguard.cfg`
* Activated ProGuard for releases

Fixes #977

### CODE REVIEW

**Comment by TranceLove** [comment]
Unable to connect to SSH servers with these proguard rules.

Having SpongyCastle alone is not sufficient for the SCP/SFTP part to function, since BouncyCastle is (as of 0.23.0, still) a dependency of [sshj](https://github.com/hierynomus/sshj), hence the regression.

Please wait, while I check if it's just copy-and-pasting SpongyCastle's rules to BouncyCastle would do.

**Comment by EmmanuelMess** [comment]
I don't understand, why would Proguard break BouncyCastle, isn't it already in Android?

**Comment by TranceLove** [comment]
> I don't understand, why would Proguard break BouncyCastle, isn't it already in Android?

Surely yes. However unfortunately from my testing without keeping BouncyCastle available sshj cannot won't be able to find them, hence not able to connect.

**Comment by VishalNehra** [comment]
SFTP seems to be working fine for me for these rules. Can't test decryption as it's currently broken on master.

**Comment by VishalNehra** [comment]
@TranceLove are you positive SFTP doesn't work for you after applying these rules?

**Comment by EmmanuelMess** [comment]
I merged @TranceLove's fix.

**Comment by TranceLove** [comment]
> @TranceLove are you positive SFTP doesn't work for you after applying these rules?

After 178dce5 it worked.

**Comment by EmmanuelMess** [comment]
@VishalNehra?

**Pull request merged**
