### PR TITLE
1921: Fix ServiceWatcherUtil NPE

### LINKED ISSUE #1921: Getting NPE after a service finishes execution
**Describe the bug**
A possible NPE as reported by @hman2 in #1912

**To Reproduce**
NPE when `ServiceWatcherUtil#stopWatch` is being called. Most possibly when a service (copy/ move) finishes execution.

**Expected behavior**
No crash.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]

**Additional context**

Stacktrace

```
07-02 14:07:09.240 D/AndroidRuntime(32609): Shutting down VM
07-02 14:07:09.241 E/AndroidRuntime(32609): FATAL EXCEPTION: main
07-02 14:07:09.241 E/AndroidRuntime(32609): Process: com.amaze.filemanager.debug, PID: 32609
07-02 14:07:09.241 E/AndroidRuntime(32609): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.amaze.filemanager.asynchronous.AbstractRepeatingRunnable.isAlive()' on a null object reference
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at com.amaze.filemanager.asynchronous.management.ServiceWatcherUtil.stopWatch(ServiceWatcherUtil.java:167)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at com.amaze.filemanager.asynchronous.services.EncryptService$BackgroundTask.onPostExecute(EncryptService.java:238)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at com.amaze.filemanager.asynchronous.services.EncryptService$BackgroundTask.onPostExecute(EncryptService.java:203)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.os.AsyncTask.finish(AsyncTask.java:667)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.os.Looper.loop(Looper.java:154)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at android.app.ActivityThread.main(ActivityThread.java:6128)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-02 14:07:09.241 E/AndroidRuntime(32609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-02 14:07:09.243 W/ActivityManager( 1825):   Force finishing activity com.amaze.filemanager.debug/com.amaze.filemanager.activities.MainActivity
```

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1921
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Oneplus 6t
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
@hman2 request you to please help with testing. Last time you posted a few crashes. This should reduce the frequency of those crashes.
Please also keep logger app on just in case, to fetch any new crash or something.
[Here's the apk](https://github.com/TeamAmaze/AmazeFileManager/actions/runs/161801535)

**Comment by hman2** [comment]
Sorry, was away for some days. Downloaded the 2 new APK, will test and comment here.

**Comment by hman2** [comment]
playstore version crashed. I removed the old Amaze Debug, installed the new, gave it the rights to the SD card (first with the initial dialog, then I forced it to gain writing rights by performing a file copy, which succeeded. Then I started SysLog and started Amaze Debug a second time, instructing it to encrypt the newly copied file. Crash.

**Comment by VishalNehra** [comment]
So the file being encrypted was in SD Card? 
Also, can you please attach the crash log (:

**Comment by hman2** [comment]
Hm, I thought I did ?!

**Pull request merged**
