### PR TITLE
Run tests on Travis

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Massive thanks for @MikeHardy for [publishing working version of a travis config for running emulator on all APIs](https://travis-ci.community/t/is-android-28-emulator-supported/1718/5).

----
<a class="imgpatreon" href="https://www.patreon.com/emmanuelmess" target="_blank">
Become a patreon</a>

### CODE REVIEW

**Comment by mikehardy** [comment]
You might be interested in the state-of-the-art version here, it's an open source app

There was some Travis ubuntu migration that caused an issue, and now we have a build-matrix with an allowable failure where we test a different JDK (if that is of interest) https://github.com/ankidroid/Anki-Android/blob/master/.travis.yml

**Comment by mikehardy** [comment]
Just for grins (since you guys are open source too :-) ) - if you examine the project I linked in for the .travis.yml you'll see an example of running the equivalent of connectedAndroidTest, but with jacoco (JAva COde COverage) integrated so you can do jacocoTestReport and actually download integrated coverage reports from multiple APIs at the same time to get aggregate coverage, in addition to your unit tests. Mix with Robolectric (also demonstrated in the Anki-Android project) and you've got some pretty powerful CI-fu. Cheers

**Comment by EmmanuelMess** [comment]
@VishalNehra not sure why the tests wouldn't be running on the device, but added the check nevertheless. Will fix the unit tests later on another PR.

**Comment by TranceLove** [comment]
Added fixes to the test cases. But seems `gradlew connectedPlayDebugAndroidTest` is still not yet passing... :/

**Comment by VishalNehra** [comment]
Test cases have been fixed on branch release/3.5 and a basic pipeline is also setup using Github actions which run Junit tests and publishes coverage on Codecy. 
However I think Github actions doesn't yet support `connectedAndroidTest`. We might be able to utilize this travis pipeline for that. 
Let's rebase this and try to run on travis.

**Comment by mikehardy** [comment]
github's macOS runners do accelerated emulation and run emulator tests for a few projects I work on, it's possible

**Comment by VishalNehra** [comment]
Ah, will check that. Thanks (:

**Pull request closed without merging**
