### PR TITLE
Fix for enabling SSL for FTP server

### LINKED ISSUE #932: Secure connection is greyed on on ftp server settings.
Using Copperhead OS lastest based on android 8 and the v3.2.1 of Amaze that ships with Fdroid.

The FTP server setting show secure connection greyed out with no indication why.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #932.

 * New BouncyCastle keystore created using [Portecle](http://portecle.sourceforge.net), with same alias and passwords
 * Enable option for enable secure connection at FTPServerFragment
 * Use DefaultSslConfiguration directly instead of SSLConfigurationFactory in FTPService to remove the need of writing keystore

Will try to write unit test later, though differences between Android and local JVM had got me a painful time to simply get things to work :/

Tested with Oneplus One running Slim7 (7.1.2) and using Filezilla to connect. Remember to enable implicit SSL at site manager.

screenshot from 2018-06-14 17-41-03

Then you should see this pops up on connect :)

screenshot from 2018-06-14 17-39-09

### CODE REVIEW

**Comment by TranceLove** [comment]
It had been working... even with my Galaxy S2 running SlimLP (5.1.1). Or you are running this on emulator?
(But 3.2.2 was also not running on emulator anyway...)

You may need to find some more clue from logcat.

**Comment by VishalNehra** [comment]
Wasn't able to pinpoint, but this was the log when I tried for first time, 
````
06-16 02:44:22.292 4445-4445/com.amaze.filemanager E/FTPService: getLocalInetAddress called and no connection
06-16 02:44:22.293 4445-4445/com.amaze.filemanager W/System.err: java.lang.NullPointerException: getLocalInetAddress returned a null value
06-16 02:44:22.294 4445-4445/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.fragments.FTPServerFragment.getFTPAddressString(FTPServerFragment.java:527)
        at com.amaze.filemanager.fragments.FTPServerFragment.updateSpans(FTPServerFragment.java:463)
        at com.amaze.filemanager.fragments.FTPServerFragment.onCreateView(FTPServerFragment.java:109)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
06-16 02:44:22.295 4445-4445/com.amaze.filemanager W/System.err:     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
````
After this whenever I try starting new server after the first time, I don't get the above logcat.
````
06-14 18:47:04.449 30968-30968/com.amaze.filemanager D/FTPService: Server is not running (null serverThread)````

**Comment by TranceLove** [comment]
From this line
```
06-16 02:44:22.292 4445-4445/com.amaze.filemanager E/FTPService: getLocalInetAddress called and no connection
```
There are a few possibilities:
 * Your device is not connected to local network (Wifi/Ethernet)
 * Your device's Wifi AP spot is not enabled
 * Or simply, system API `WifiManager.isWifiApEnabled()` is not available on your ROM (which is almost impossible)

And from what I read from FTPService codes on this/master branch and `hotfix-zip` (which goes to 3.2.2 release) network address detection code wasn't changed.

**Comment by EmmanuelMess** [comment]
Server side:
```
Estado:	Conectando a 192.168.0.10:2211...
Estado:	Conexión establecida, esperando el mensaje de bienvenida...
Error:	Connection timed out after 20 seconds of inactivity
Error:	No se pudo conectar al servidor
```

Android logcat (redacted):
```
06-17 15:45:36.017 com.amaze.filemanager W/System.err: [NioProcessor-6] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - CREATED
06-17 15:45:36.020 com.amaze.filemanager W/System.err: [pool-10-thread-3] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - OPENED
06-17 15:45:56.055 com.amaze.filemanager W/System.err: [pool-10-thread-3] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - CLOSED
06-17 15:46:01.084 com.amaze.filemanager W/System.err: [NioProcessor-7] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - CREATED
06-17 15:46:01.086 com.amaze.filemanager W/System.err: [pool-10-thread-3] INFO org.apache.ftpserver.listener.nio.FtpLoggingFilter - OPENED
```

**Comment by TranceLove** [comment]
@EmmanuelMess did you enable Implicit SSL when creating connection at Filezilla?

**Comment by TranceLove** [comment]
Added 5dc922a to prove it's working with/without SSL. Remember to grant app permission to access device storage, if necessary, or file listing will not work.

**Comment by VishalNehra** [comment]
@EmmanuelMess please review,, we've the release on hold.

**Comment by VishalNehra** [comment]
Yes, can create a new issue for the same.

**Comment by TranceLove** [comment]
> Files aren't actually getting created and ip is cut ("sftp://⏎[...]"), but I suppose that happened in master too.

Please raise issue - this doesn't look like things I've seen yet.

**Comment by EmmanuelMess** [comment]
> Files aren't actually getting created

My mistake, file are getting created.

**Pull request merged**
