### PR TITLE
Fixed Issue #2141 - Crash on screen rotate in grid view

### LINKED ISSUE #2141: Crash on screen rotate in grid view
Marc, [14-Dec-2020 at 3:16:51 PM]:
Crash on rotating phone.
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.2
* OS: Linux Android 11 - 30
* Device: sargo
* Model: Pixel 3a
* Product: sargo
<details><summary><b>Crash log </b></summary><p>

`
java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
 at androidx.recyclerview.widget.GridLayoutManager.getSpaceForSpanRange(GridLayoutManager.java:352)
 at androidx.recyclerview.widget.GridLayoutManager.measureChild(GridLayoutManager.java:722)
 at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:597)
 at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
 at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
 at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
 at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
 at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
 at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
 at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
 at android.view.View.layout(View.java:22844)
 at android.view.ViewGroup.layout(ViewGroup.java:6389)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)

at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
 at android.view.Choreographer.doCallbacks(Choreographer.java:796)
 at android.view.Choreographer.doFrame(Choreographer.java:731)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7660)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

`
</details>
<hr>

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2141

#### Release  
Addresses hotfix/3.5.3
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Realme Narzo 20A
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by EmmanuelMess — COMMENTED** [review]
Seems like it would be a good idea to organize the code, line 279 creates another `GridLayoutManager`, line 340 changes the amount of columns. Maybe the two grid layout managers should be set up in explicitly different ways to prevent further issues?

**Comment by VishnuSanal** [comment]
> Seems like it would be a good idea to organize the code, line 279 creates another `GridLayoutManager`, line 340 changes the amount of columns. Maybe the two grid layout managers should be set up in explicitly different ways to prevent further issues?

I'm sorry I didn't get you :( Could you please elaborate it more? Thanks :D

**Comment by EmmanuelMess** [comment]
> > Seems like it would be a good idea to organize the code, line 279 creates another `GridLayoutManager`, line 340 changes the amount of columns. Maybe the two grid layout managers should be set up in explicitly different ways to prevent further issues?
> 
> I'm sorry I didn't get you :( Could you please elaborate it more? Thanks :D

Is there a way to separate the code for -1 or 0 columns from the other code so that it becomes more difficult to make mistakes?

**Comment by VishnuSanal** [comment]
@EmmanuelMess Would a function work? Like getCoulumns(); or something similar Thanks :)

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess Would a function work? Like getColumns(); or something similar Thanks :)

Yes.

**Comment by VishnuSanal** [comment]
> > @EmmanuelMess Would a function work? Like getColumns(); or something similar Thanks :)
> 
> Yes.

I'll do that :D

**Review by VishalNehra — APPROVED** [review]

**Review by TranceLove — APPROVED** [review]
Looks good on LG Nexus 5x running AOSPExtended (9.0), no crash no matter how I rotate the screen while in grid view mode.

Voting +1.

**Pull request merged**
