### PR TITLE
Fix failing build

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Manual tests
- [x] Done  
 
#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #2789

### CODE REVIEW

**Review by EmmanuelMess — DISMISSED** [review]

**Comment by EmmanuelMess** [comment]
What's the rationale behind removing the builds?

**Comment by VishnuSanal** [comment]
> What's the rationale behind removing the builds?

It was failing all these while because we were building release flavours. Also, as we discussed on Telegram, release should build fine if debug builds.

**Comment by EmmanuelMess** [comment]
> It was failing all these while because we were building release flavours.

I still think building release flavour is indicative of how well releases are, for example, playRelease alerts to a lot of unused strings, also, the debug keystore should work out of the box for amaze, so that play release can be easily tested.

**Comment by VishnuSanal** [comment]
> > It was failing all these while because we were building release flavours.
> 
> I still think building release flavour is indicative of how well releases are, for example, playRelease alerts to a lot of unused strings, also, the debug keystore should work out of the box for amaze, so that play release can be easily tested.

Agreed, but, release build requires keystore etc & we can't expose them.

**Pull request merged**
