### PR TITLE
Update the PR template to have less text

### PR DESCRIPTION
**Pull request by EmmanuelMess**
## Description
Update the PR template to have less text on average, most options are still there, but commented.
Also added a header.

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishnuSanal — APPROVED** [review]
Awesome work @EmmanuelMess :) I give my +1 

Just a suggestion, specifying how to run `spotlessApply` & `assembledebug` would be a cherry in the icing IMO

**Comment by VishalNehra** [comment]
Suggest to decrease issue template text as well.

**Comment by EmmanuelMess** [comment]
> Suggest to decrease issue template text as well.

That would be another PR

**Comment by EmmanuelMess** [comment]
> Just a suggestion, specifying how to run `spotlessApply` & `assembledebug` would be a cherry in the icing IMO

That would have to be in a "project setup" guide, something like CONTRIBUTING.md

**Review by TranceLove — APPROVED** [review]

**Pull request merged**
