### PR TITLE
Remove callback to MainActivity's DataChangeListener implementation f…

### LINKED ISSUE #1346: CalledFromWrongThreadException
v3.2.2 from F-Droid

This should be a trivial bug. GUI should not be updated from a background thread.

```
android.view.ViewRootImpl$CalledFromWrongThreadException
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6556)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:907)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.view.View.requestLayout(View.java:18728)
	at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1265)
	at android.view.View.requestLayout(View.java:18728)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
	at android.view.View.requestLayout(View.java:18728)
	at android.widget.AbsListView.requestLayout(AbsListView.java:1975)
	at android.widget.ListView.setAdapter(ListView.java:519)
	at com.amaze.filemanager.activities.MainActivity.refreshDrawer(MainActivity.java:1519)
	at com.amaze.filemanager.activities.MainActivity.onBookAdded(MainActivity.java:2188)
	at com.amaze.filemanager.utils.DataUtils$1.run(DataUtils.java:210)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

### PR DESCRIPTION
**Pull request by VishalNehra**
Fixes #1346

### CODE REVIEW

**Comment by TranceLove** [comment]
Actions to save data to database continued to work after applying changeset. I'd vote a +1.

(Tested with Pixel 2 emulator running 7.1.1)

**Comment by EmmanuelMess** [comment]
Shouln't those calls be explicitly in main thread?

**Comment by VishalNehra** [comment]
@EmmanuelMess  yes, they're called from main thread. I don't see the need to write extra code to execute them on main thread when they're already being called from main thread.

**Comment by EmmanuelMess** [comment]
Half the functions in that class are thread safe, and some of the functions you changed have redundant lockings. Maybe add a javadoc to prevent future mishaps:

```
/**
 * ONLY CALL FROM MAIN THREAD
 */
```

**Comment by VishalNehra** [comment]
Done

**Comment by EmmanuelMess** [comment]
Good enough, I suppose.

**Pull request merged**
