### PR TITLE
Bugfix/directory perms

### LINKED ISSUE #1497: Root Explorer: weird display and some symlink to dir treated as files
As you can see from the image attached, the **Root Explorer** screen displays a weird string instead of the plain file name. It seems the output of the `ls -l` command.
Also some symlink to directories are treated as files, so if I tap on `/etc` or `/sdcard` I got the **Open As** menu instead of changing directory.
Running Amaze version 3.2.2 from F-Droid, on Android Oreo 8.1.0. Root `su` is provided by Magisk 17.3
screen1

### LINKED ISSUE #1807: Can't access /mnt when root browsing is enabled.
Most of the folders in the root directory becomes unaccessible when root browsing is enabled.

Before root access:
https://pasteboard.co/IOqsYTl.png

After root access (can't browse /mnt):
https://pasteboard.co/IOqtjAm.png
https://pasteboard.co/IOqtvXH.png

I'm using GenyMotion and I'm trying to give an specific app permissions to write on a mounted folder.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1497 
Fixes #1807 
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by TranceLove** [comment]
On Samsung Galaxy S2 (GT-i9100) running SlimLP (5.1.1) rooted + SuperSU, the bundled(?) busybox does not support the -c parameter, hence showing empty file list. When run the command directly from `su`-ed `adb shell`, command exited with an return code of 1.

Busybox version signature `BusyBox v1.22.1 bionic (2016-05-15 21:00 +0300) multi-call binary`

Not sure if I should ask for a fallback option... although I should migrate the phone to Magisk and install Busybox from there, if my device could still endure. ;)

Other devices passing the test:

- GPD XD running LegacyROM (4.4.4), Busybox `BusyBox v1.24.1-Stericson (2015-11-06 19:11:24 EST) multi-call binary`
- Fairphone 3 running LineageOS 16.0, Busybox installed via Magisk `BusyBox v1.31.1-osm0sis (2020-05-06 20:45:25 ADT) multi-call binary`
- LG Nexus 5x running AOSPExtended (9.0), Busybox installed via Magisk `BusyBox v1.30.1-osm0sis (2019-02-28 18:48:08 AST) multi-call binary`
- Oneplus 2 running AOSPExtended (7.1.2), Busybox installed via Magisk `BusyBox v1.31.1-osm0sis (2019-11-01 17:49:17 ADT) multi-call binary`

Additionally, per discussion on Telegram group, as @EmmanuelMess suggested the class/interface structure is unnecessarily complex (or flattened to multiple classes of single function implementation), may you consider using `companion object` and `@JvmStatic` to write the commands so they can still be called as Java's static methods and grouped together in fewer classes?

**Comment by VishalNehra** [comment]
Thanks for testing @TranceLove 
I'll do something for the fallback. Already do have a fallback to `ls` if stat binary is not found at /system/bin or /system/xbin. So shouldn't be a problem keeping this as fallback as well. 
As for the design, I've already removed the interfaces, as for using companion object, I think singleton class and one seperate implementation class for each command is a better approach and will keep things less complex. Using companion object won't allow to use inheritance of common root command operations as well.

**Comment by EmmanuelMess** [comment]
> I think singleton class and one seperate implementation class for each command is a better approach and will keep things less complex.

Why less complex?

**Comment by VishalNehra** [comment]
@EmmanuelMess Remember earlier what we had.. single class trying to handle all the commands. It had so much complexity as i tried to scale it to handle ls and stat both
This type of architecture is single responsibility and more scalable.

**Comment by EmmanuelMess** [comment]
> Remember earlier what we had.. single class trying to handle all the commands. It had so much complexity as i tried to scale it to handle ls and stat both

With extension functions one can have a class separated into a lot of files.

**Comment by EmmanuelMess** [comment]
Open settings, enable root explorer, crash.

Logcat:
```
03-16 12:24:37.150 1776-1776/com.amaze.filemanager.debug W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4155d908)
03-16 12:24:37.155 1776-1776/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at com.amaze.filemanager.ui.activities.PreferencesActivity.onOptionsItemSelected(PreferencesActivity.java:139)
        at android.app.Activity.onMenuItemSelected(Activity.java:2546)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
        at android.view.View.performClick(View.java:4091)
        at android.view.View$PerformClick.run(View.java:17081)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:4987)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
        at dalvik.system.NativeStart.main(Native Method)
```

Android 4.1.2

**Review by EmmanuelMess — DISMISSED** [review]
Code seems ok, although all the methods should not have their own classes only their own files.
Tests on physical phone pass, on rooted Motorola RAZR D3.

**Comment by EmmanuelMess** [comment]
@VishalNehra What happened?

**Comment by VishalNehra** [comment]
@EmmanuelMess Nope. There was a comment given by @TranceLove to fallback to ls if stat fails. Just fixed that. 
Ready to be reviewed now.
Any new changes pushed automatically dismisses previous approvals in PR.

**Review by TranceLove — APPROVED** [review]
Tested on Samsung Galaxy S2 (GT-i9100) running SlimLP (5.1.1), LG Nexus 5x running AOSPExtended (9.0) and GPD XD running LegacyROM (4.4.4) with Busybox versions exactly the same as [above](https://github.com/TeamAmaze/AmazeFileManager/pull/2063#issuecomment-717991755), all devices could successfully list files at root after enabling root explorer and granted superuser from SuperSU/Magisk.

Functionally OK to go. Voting +1.

**Review by EmmanuelMess — APPROVED** [review]
Code seems ok, although all the methods should not have their own classes only their own files.
Tests on physical phone pass, on rooted Motorola RAZR D3.

**Pull request merged**
