### PR TITLE
ProgressHandler's fields are now atomically updated without synchronizing the class

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Moved ProgressHandler.speedRaw to local variable
* ProgressHandler's fields are now atomically updated without synchronizing the class

Required by #1362.
Needed for #1306.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Another solution is to make the whole class immutable, and create a new object for each change, what do you think?

**Comment by VishalNehra** [comment]
Immutable for this class is not ideal. It's updated multiple times every second. We'll be left with thousands of dangling pointers for GC to be collected at the end of each operation. 
Also, please use ````Atomic```` data types if you plan to remove synchronized from methods returning booleans/ints.

**Comment by VishalNehra** [comment]
They were atomic until you removed synchronized from method signature.

**Comment by EmmanuelMess** [comment]
> They were atomic until you removed synchronized from method signature.

[They ARE atomic.](https://stackoverflow.com/a/4756578/3124150)

**Comment by EmmanuelMess** [comment]
> Immutable for this class is not ideal. It's updated  multiple times every second. We'll be left with thousands of dangling  pointers for GC to be collected at the end of each operation.

If I reduced the update rate, would immutability be a better idea?

**Comment by VishalNehra** [comment]
This is not true... The assignment is not atomic, while an assignment operation is performed, it is modified in the memory, while assignment to memory if any other thread accesses it, older value might be returned. If we use Atomic classes, the whole assignment to memory part will be atomic hence only the most recent value will be returned by another thread.
We need either synchronised or Atomic/volatile variables.

**Comment by VishalNehra** [comment]
Reduce the rate? What do you mean? Current code avoids any redundant code in operation so that it is the fastest possible. Anything more you write will effect the performance of the operation.
Why do you intend to fix something that's not broken in the first place?

**Comment by EmmanuelMess** [comment]
> Anything more you write will effect the performance of the operation.

Thought this only communicated information back to the notification, my mistake.

**Comment by EmmanuelMess** [comment]
> Reduce the rate? What do you mean? Current code avoids any redundant code in operation so that it is the fastest possible. Anything more you write will effect the performance of the operation.
Why do you intend to fix something that's not broken in the first place?

I'm not, I need to create more smaller PRs, and I've gotten ahead of myself suggesting the rate reduction. Sorry for the inconvenience.

**Comment by EmmanuelMess** [comment]
[Fixed](https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html).

> Reads and writes are atomic for all variables declared volatile (including long and double variables).

**Comment by VishalNehra** [comment]
>  I'm not, I need to create more smaller PRs, and I've gotten ahead of myself suggesting the rate reduction. 

Please work on separate branch then, and create all smaller PRs to that branch. It is not recommended to push smaller test PRs in master.

**Comment by EmmanuelMess** [comment]
> Please work on separate branch then, and create all smaller PRs to that branch. It is not recommended to push smaller test PRs in master.

This is by no means a "test PR" it is  part of a bigger change, but functional and useful by itself.

**Comment by VishalNehra** [comment]
Yes, it's useful by itself that's why I approved. But if something is part of a bigger change, you should probably work on that bigger thing in a separate branch instead of creating PRs for master. That'll leave master unstable.

**Comment by EmmanuelMess** [comment]
> That'll leave master unstable.
I just divide the bigger change into chunks that are stable, just as this is stable.

**Pull request merged**
