### PR TITLE
Hotfix/3.8.2 to master

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by EmmanuelMess — DISMISSED** [review]

**Review by VishnuSanal — APPROVED** [review]

**Review by TranceLove — APPROVED** [review]
All green, I think it's good to go.

Meanwhile I will find a way to "correct" those threading issues breaking the tests, namely #3228 and possibly moving the servers out of JVM at all.

**Comment by EmmanuelMess** [comment]
Build broke?

**Comment by VishnuSanal** [comment]
> Build broke?

nops, merging...

**Comment by VishnuSanal** [comment]
> > Build broke?
> 
> nops, merging...

but, um... now CI fails on the master branch

**Pull request merged**
