### PR TITLE
Added setting to open files in new stack

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Added setting to open files in new stack (#725).
* Cleaned code a bit.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
I need to test with DbViewer, but don't know which file extensions it opens.

**Comment by EmmanuelMess** [comment]
Mind explaining?

**Comment by vishal0071** [comment]
My bad, but we still need to discuss the feasibility of this feature.

**Comment by EmmanuelMess** [comment]
Do speak your mind, and remember that this is turned off by default and is under "Advanced" in the settings category.

**Pull request merged**
