### PR TITLE
Fix NPE when popup is opened with split screen

### LINKED ISSUE #2752: NPE when clicking on popup items after triggering system split screen
## Exception
* App Name: Amaze File Manager
* Package: com.amaze.filemanager
* Version: 3.6.1
* User Action: UI Error
* Request: Application crash
* OS: Linux Android 8.1.0 - 27
* Device: TB-8704X
* Model: Lenovo TB-8704X
* Product: TB-8704X
<details><summary><b>Crash log </b></summary><p>

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
 at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialog(GeneralDialogCreation.java:425)
 at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.showPropertiesDialogWithPermissions(GeneralDialogCreation.java:403)
 at com.amaze.filemanager.ui.ItemPopupMenu.onMenuItemClick(ItemPopupMenu.java:93)
 at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:167)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
 at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

</details>
<hr>

Reporter: shuvashish76

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   

Fixes #2752

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
I'm afraid that it still crashes for me.

How will adding `@NonNull` & changing to `requireActivity()` solve NPE? `requireActivity()` is `getActivity()` under the hood.

```
@NonNull
    public final FragmentActivity requireActivity() {
        FragmentActivity activity = getActivity();
        if (activity == null) {
            throw new IllegalStateException("Fragment " + this + " not attached to an activity.");
        }
        return activity;
    }
```

**Comment by EmmanuelMess** [comment]
> I'm afraid that it still crashes for me.
> 
> How will adding `@NonNull` & changing to `requireActivity()` solve NPE? `requireActivity()` is `getActivity()` under the hood.

Not that, the `mainFragment.getActivity()` to `mainActivity` would fix it, tested on AVD Android 11. Where are you replicating the bug?

**Comment by VishnuSanal** [comment]
@EmmanuelMess > Where are you replicating the bug?

On a real device:

 - Device: Realme Narzo 20A
 - OS: Android 10
 - Rooted: No

**Comment by VishalNehra** [comment]
Bunch of conflicts here

**Comment by VishalNehra** [comment]
@VishnuSanal  review here please.

**Comment by VishnuSanal** [comment]
@VishalNehra As said previously, everything except Rename & Add to Bookmarks works (getting IllegalStateException for these)

**Comment by EmmanuelMess** [comment]
> @VishalNehra As said previously, everything except Rename & Add to Bookmarks works (getting IllegalStateException for these)

These are issues of another issue

**Comment by VishnuSanal** [comment]
> > @VishalNehra As said previously, everything except Rename & Add to Bookmarks works (getting IllegalStateException for these)
> 
> These are issues of another issue

Yess! No offense :(

**Comment by VishalNehra** [comment]
Please approve the pr if it's good from your side @VishnuSanal

**Review by VishnuSanal — DISMISSED** [review]

**Pull request merged**
