### PR TITLE
Feature/1827 Add android-tv navigation

### LINKED ISSUE #1827: Works on AndroidTV but could be better
Hey there.

The good news, v3.4.2 works on my nvidia shieldTV (androidtv 9 | nvidia os v8.0.1).
The bad news, it is very difficult to see the current selected area.

It would be awesome if we could check if it is an firetv or androidtv device and then highlight more the selected areas. Otherwise a trigger could be DPAD control.

THX for your work. Nice to have an ES-FileExplorer alternative.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   

Fixes #1827 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Can an android emulator be created for testing this?

**Comment by VishalNehra** [comment]
@EmmanuelMess Yes. You can create Android tv emulator.

**Comment by TranceLove** [comment]
When testing on TV emulator running Android 7, at About screen, scroll down with keyboard didn't shrink the logo

スクリーンショット 2021-06-03 12-46-11

but not with mouse swipe up

スクリーンショット 2021-06-03 12-50-03

**Comment by VishalNehra** [comment]
Should be fixed now @TranceLove

**Review by TranceLove — APPROVED** [review]
Looks OK on Android TV emulator running Android 7.

**Pull request merged**
