### PR TITLE
Fix: replace add icon with cut icon (drag n drop)

### LINKED ISSUE #2544: Drag and drop icon shows a plus
**Describe the bug**
Drag and drop icon shows a plus, not the icon of the thing/s being dragged.

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #2544

Hi @VishalNehra!

I don't think is quite right yet! I just replaced the add icon with the cut icon for now (a small win that I couldn't find where to actually change the code)

Do we need to add a new custom cut/copy icon, or does one already exist?

Looking forward to your review!

thanks!

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
> Do we need to add a new custom cut/copy icon, or does one already exist?

It probably doesn't exist. A fast look at https://fonts.google.com/icons?selected=Material+Icons&icon.query=copy doesn't reveal any promising icons IMO.

**Comment by VishalNehra** [comment]
Something like this perhaps? I've seen this somewhere 🤔 
Ps. pardon my drawing skills 😅

**Comment by EmmanuelMess** [comment]
> 
> Something like this perhaps? I've seen this somewhere thinking
> Ps. pardon my drawing skills sweat_smile

Yes, like that.

**Comment by VishalNehra** [comment]
Closing till we have a relevant icon

**Pull request closed without merging**
