### PR TITLE
Debug version name is now "Amaze Debug" and other fixes

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Copied private color from MaterailDialog lib
* Update support lib to 28.0.0
* Removed unnecessary buildToolsVersion declaration in build.gradle 
* Debug version's name is now "Amaze Debug" and package is suffixed with ".debug"

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
```
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.amaze.filemanager/.activities.MainActivity }
Error type 3
Error: Activity class {com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity} does not exist.
```

It seems Android Studio is trying to launch `com.amaze.filemanager.activities.MainActivity` instead of `com.amaze.filemanager.debug.activities.MainActivity`, have you cleaned?

> Also, does this change intends to allow both debug and production versions to run side-by-side?

Yes,

**Comment by TranceLove** [comment]
I tried this:

* Apply the changeset to current master (ec7c02068)
* Build `fdroidRelease` and install
* Build -> Clean project
* Change build variant to `fdroidDebug`
* Build -> Clean project
* Build `frdoidDebug` and install
* This dialog pops up

screenshot from 2018-12-31 12-26-27

Also tried this:

* Apply the changeset to current master (ec7c02068)
* Build `playRelease` and install
* Build -> Clean project
* Change build variant to `playDebug`
* Build -> Clean project
* Build `playDebug` and install
* This dialog pops up

screenshot from 2018-12-31 11-08-06

Any help?

**Comment by EmmanuelMess** [comment]
You have to manually uninstall the old debug version, because the package names differ, you would otherwise be installing the new version inside the older version (`com.amaze.filemanager.debug` is inside `com.amaze.filemanager`).

**Comment by VishalNehra** [comment]
Production package name remains the same, right? Because play store won't accept a change in package name.

**Comment by TranceLove** [comment]
@EmmanuelMess still didn't get things to work until explicitly separate the application IDs in FILE_PROVIDER names. See EmmanuelMess/AmazeFileManager#20

**Pull request merged**
