### PR TITLE
Fix: Back navigation shown as search result

### LINKED ISSUE #1716: When "Back Navigation" is enabled, the .. folder is shown as a search result
**Expected behavior**

When search results are populated, `..` folder (back navigation) should not be included in the list of results. 

**Actual behavior**

The `..` folder (back navigation) is shown as a search result.

**Steps to reproduce**
1. Go to "Settings" and enable "Back navigation" under "General" category.
1. Search for files. 

**System info**
- Phone model: Google Pixel 2
- Android version: 10
- Rooted: No

### PR DESCRIPTION
**Pull request by Soroyesodiq**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1716 
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Android 7.0
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
**Screenshot before searching for a folder**
before searching

**Screenshot during search**
during searching

**Search results screenshot**
search result

### CODE REVIEW

**Comment by VishalNehra** [comment]
Thanks for the PR. Can you please rebase with release/3.5

**Comment by Soroyesodiq** [comment]
> Thanks for the PR. Can you please rebase with release/3.5

I have changed the base branch to release/3.5. Thanks for the comment.

**Comment by VishalNehra** [comment]
I mean rebase it.. take a pull from release/3.5 and fix the merge conflicts.

**Comment by VishalNehra** [comment]
Try to run `./gradlew spotlessapply` for build to be successful.

**Comment by Soroyesodiq** [comment]
> Try to run `./gradlew spotlessapply` for build to be successful.

Thanks for putting me through. I really appreciate your help.

**Comment by VishalNehra** [comment]
Build test apk

**Comment by VishalNehra** [comment]
A few questions here
1. Why introduce a new variable, can we not use the existing `results` variable? I think that variable also denotes if the list being displayed is of search results or not.
2. This variable is not being persisted in screen rotation/state change. Just rotate device after search, back button will come up again.

**Comment by Soroyesodiq** [comment]
> A few questions here
> 1. Why introduce a new variable, can we not use the existing `results` variable? I think that variable also denotes if the list being displayed is of search results or not.
> 2. This variable is not being persisted in screen rotation/state change. Just rotate device after search, back button will come up again.

Okay, I will work on that.

**Comment by Soroyesodiq** [comment]
> A few questions here
> 
> 1. Why introduce a new variable, can we not use the existing `results` variable? I think that variable also denotes if the list being displayed is of search results or not.
> 2. This variable is not being persisted in screen rotation/state change. Just rotate device after search, back button will come up again.

These are the device screenshot when i used the existing `results` variable.
**BEFORE SEARCHING**
before searching 1
 
**DURING SEARCHING**
during searching 1

**SEARCH RESULTS**
search result 1

**AFTER SCREEN ROTATION**
view during screen rotation

**Comment by VishalNehra** [comment]
I'm sorry, but this still needs some work.
I've changed the code [here](https://github.com/TeamAmaze/AmazeFileManager/commit/ffa424fd0718ee26b8158c22fb777d767e54809b), can you please test it and change in your PR accordingly?

**Comment by Soroyesodiq** [comment]
> I'm sorry, but this still needs some work.
> I've changed the code [here](https://github.com/TeamAmaze/AmazeFileManager/commit/ffa424fd0718ee26b8158c22fb777d767e54809b), can you please test it and change in your PR accordingly?

Okay, i will do that.

**Comment by Soroyesodiq** [comment]
> I'm sorry, but this still needs some work.
> I've changed the code [here](https://github.com/TeamAmaze/AmazeFileManager/commit/ffa424fd0718ee26b8158c22fb777d767e54809b), can you please test it and change in your PR accordingly?

I have tested the changes and it worked perfectly fine.

**Pull request merged**
