### PR TITLE
Adds short descriptions for quick access and recent files

### LINKED ISSUE #2896: Short description of Quick access & Recent files feature
mention a short description of what it does

_Originally posted by @shuvashish76 in https://github.com/TeamAmaze/AmazeFileManager/discussions/2831_

-----

This now has a bounty, [here](https://app.bountysource.com/issues/104758276-short-description-of-quick-access-recent-files-feature), bounty expires in one month from 2022-01-14, if you have been working, please alert us so that we can extend it.

Please claim after a PR fixing this issue is accepted.
Remember that you can also back the issue adding to the bounty!

### PR DESCRIPTION
**Pull request by nicbn**
## Description

* Adds short descriptions for quick access and recent files in the settings.

image

#### Issue tracker   

Fixes #2896
  
#### Manual tests

- [x] Done  

- Device: Android Emulator, Pixel 3a
- OS: API 30

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@VishalNehra please confirm the descriptions are correct.

**Comment by EmmanuelMess** [comment]
Thanks for the contribution!

**Comment by VishalNehra** [comment]
'Files recently accessed through Amaze' or using Amaze IMO

**Comment by nicbn** [comment]
Updated

**Review by EmmanuelMess — APPROVED** [review]

**Review by VishnuSanal — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
https://www.transifex.com/amaze/amaze-file-manager/
You need to translate languages other than english through transifex as these changes will be overwritten by them. Approving this for now.

**Comment by EmmanuelMess** [comment]
[Here](https://github.com/TeamAmaze/AmazeFileManager/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ABounty) are some other bounties.

**Pull request merged**
