### PR TITLE
Issue #3394

### LINKED ISSUE #3394: Rotate device and search, rotate again, then keyboard still appear
**Describe the bug**
Rotate device and search, rotate again, then keyboard still appear(should disappear)

**To Reproduce**
1. rotate devices
2. Click on search
3. rotate again
4. See keyboard still appear

**Expected behavior**
After step 3, the keyboard should disappear

**video**

https://user-images.githubusercontent.com/31406320/178173199-a00a78db-ef2f-4729-8520-6b1ba43a24aa.mp4

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [ Android 8]
 - Rooted: [e.g. No]
 - Version: [3.7.2]

**Additional context**
Sometimes, it behaves normally on AmazeFileManager 3.4.2, the keyboard disappear after rotation

### PR DESCRIPTION
**Pull request by Burhan7777**
## Description
if the screen was rotated from the landscape orientation with searchview opened keyboard won't go away in portrait mode. This has been fixed.

#### Issue tracker   

Fixes #3394

  
#### Manual tests
- [X] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [X] `./gradlew assembledebug`
- [X] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by Burhan7777** [comment]
Solves issue #3394.

**Comment by VishalNehra** [comment]
Please run `./gradlew spotlessApply` in local to fix build failure here

**Comment by Burhan7777** [comment]
@VishalNehra ran spotlessApply and spotlessCheck , build was successful

**Comment by VishalNehra** [comment]
@Burhan7777 Can you push those changes?

**Comment by Burhan7777** [comment]
pushed

**Comment by Burhan7777** [comment]
There is something deprecated in cloudStreamServer.java which is probably causing the problem. How to proceed ?

**Comment by TranceLove** [comment]
@Burhan7777 For the signing.properties not found problem, may you just change to debug variant and try again?

**Comment by TranceLove** [comment]
Then for the build failures... sorry, my mistake for not raising API requirements at submodules. Please wait - will raise PR for that tonight.

**Comment by TranceLove** [comment]
@Burhan7777 please see after #3719 your build can go through. I tested it with this PR on my desktop and the build (including tests) went fine.

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
works great & fixes the issue specified. please revert the changes made to `MainActivity.java`

**Comment by Burhan7777** [comment]
I have made no changes to the MainActivity.java

**Comment by VishnuSanal** [comment]
> I have made no changes to the MainActivity.java

Yeah, but you've inadvertently made changes to MainActivity & have pushed those changes; see the files section of this PR. Please revert those changes.

**Comment by Burhan7777** [comment]
oh sorry. Reverted those changes and pushed it.

**Review by VishnuSanal — APPROVED** [review]

**Comment by Burhan7777** [comment]
All checks have been done please approve it. Thank you so much for everyone's help.

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Thanks for contributing. This issue has a bounty which you can claim [here](https://app.bountysource.com/issues/116981342-rotate-device-and-search-rotate-again-then-keyboard-still-appear)

**Comment by VishalNehra** [comment]
Please try to minimise commit count next time for small fixes. This should've been single commit change. You could've force pushed at the end with all changes in a single commit.

**Pull request merged**
