### PR TITLE
Fixed default tab storage

### LINKED ISSUE #1043: Both tabs start with root set as home
When Amaze is installed for the first time, both tabs are set to root as home. I suspect this is due to new changes in rewritten navigation drawer code.
Please make changes so that left one is set to root and right tab which is set by default is set to storage.

### LINKED ISSUE #1067: Home for right tab set to '/' instead of internal storage
The default home for right tab is set to root instead of internal storage.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Code cleanup in TabFragment
* Fixed storage paths not getting saved correctly in Drawer
* Better handling of null storages when creating Tabs
* If the home for a tab is set to root the rootmode pref is activated

Fixed #1043 
Fixed #1067
and not #1070

### CODE REVIEW

**Comment by TranceLove** [comment]
Seems it can fix mentioned problems when tested on Lollipop emulator.

If the conclusions of #1043 and #1067 is to make both tabs as internal storage as said

> Neither should be root, as on first open the "rootmode" preference wouldn't be set to true.

I'd vote a +1.

**Comment by EmmanuelMess** [comment]
It will resort to making both internal storage if it doesn't currently have another storage. If there is no internal storage it will activate "rootmode" and set both to root.

**Comment by EmmanuelMess** [comment]
If plug a mass storage device on first start of Amaze it can be set as home (if no SD is present), if the device is then removed I have no idea what path the tab will show.

**Comment by EmmanuelMess** [comment]
@TranceLove?

**Comment by TranceLove** [comment]
Yeap, I'm good. +1.

**Pull request merged**
