### PR TITLE
Bump version number to v3.2.2

### PR DESCRIPTION
**Pull request by EmmanuelMess**
And with this I'll release, so voice mistakes here.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@VishalNehra you have been releasing for the past 4 years, any advice?

**Comment by VishalNehra** [comment]
Release in batches, but since there's a minor fix which is well tested, there shouldn't be a problem to release for 100% of target users. Also, any change in listing (new version/description change) takes around 1 hour to reflect on Play Store.
Other than that, there's not much to tell, it's a simple process. Just remember to keep keystore private and safe.

**Comment by EmmanuelMess** [comment]
Done.

**Comment by EmmanuelMess** [comment]
Now, what about FDroid?

**Pull request merged**
