### PR TITLE
Feature/1586 App shortcuts

### LINKED ISSUE #1586: long icon press shortcut
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

For example there may be "+" actions like New file or New folder.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   

Fixes #1586 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Whats the empty item at the top?


Is there a way to remove the "Leaks" item?

**Comment by VishnuSanal** [comment]
> Is there a way to remove the "Leaks" item?

Yes, comment that line in `build.gradle` and uninstall & reinstall the app

**Review by EmmanuelMess — APPROVED** [review]
Very well, testing this seems to work. An issue should be created after this is merged to add support for dark theme.

**Comment by VishalNehra** [comment]
Dark theme is already supported here CMIIW

**Pull request merged**
