### PR TITLE
Move classes to new file_operations module

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
@TranceLove I've had to duplicate Shadow files back into :app so that tests compile, if I don't it tells me the file doesn't exist. Even if I do "testImplements project(:file_operations)" it doesn't find the files. Any ideas?

**Comment by TranceLove** [comment]
> @TranceLove I've had to duplicate Shadow files back into :app so that tests compile, if I don't it tells me the file doesn't exist. Even if I do "testImplements project(:file_operations)" it doesn't find the files. Any ideas?

Sorry for the late reply.

Though [there is a `java-test-fixtures` plugin available](http://michaelevans.org/blog/2019/09/21/stop-repeating-yourself-sharing-test-code-across-android-modules/), [Android doesn't support this](https://stackoverflow.com/questions/53904747/gradle-module-output-configuration-for-test-dependencies-only) - [ticket is still open](https://issuetracker.google.com/issues/139438142). So sorry, this is what we can do for now, if we are not going to use any hacky approaches.

**Comment by EmmanuelMess** [comment]
@VishalNehra need help with the very large `startCopy()`.

**Review by TranceLove — DISMISSED** [review]

**Comment by EmmanuelMess** [comment]
@VishalNehra check needed

**Review by TranceLove — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Merged, but please don't work on something without creating an issue and marking the issue to specific release.

**Pull request merged**
