### PR TITLE
Fix drawer width

### PR DESCRIPTION
**Pull request by VishalNehra**
Fixes drawer width in landscape mode
screenshot_20180226-115159

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
AFAIK NavigationView has the standard width, why make it wider? Making the white space smaller would be better.

**Comment by TranceLove** [comment]
OK, I read [the spec](https://material.io/guidelines/patterns/navigation-drawer.html) via [here](https://android.jlelse.eu/navigation-drawer-styling-under-material-design-f0767882e692) saying

> Maximum width: The maximum width of the nav drawer is 280dp on mobile and 320dp on tablet. This is calculated by multiplying the standard increment by five (the standard increment is 56dp on mobile and 64dp on tablet).

I think it's the squeezed drawer header image that made us feel uncomfortable?

**Comment by VishalNehra** [comment]
@EmmanuelMess navigation view is also a view just like any other. You set it to wrap_content it would just wrap around the view bounds. You gotta set it to a defined width. And ````@dimen/drawer_width```` is a standard width followed by many material design apps including Google's own apps.

**Comment by EmmanuelMess** [comment]
Google doesn't really follow the Material Guidelines...
Also as per [Documentation](https://developer.android.com/reference/android/support/design/widget/NavigationView.html):

> Represents a standard navigation menu for application. The menu contents can be populated by a menu resource file.
> 
> NavigationView is typically placed inside a DrawerLayout.
> ```xml
>  <android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
>      xmlns:app="http://schemas.android.com/apk/res-auto"
>      android:id="@+id/drawer_layout"
>      android:layout_width="match_parent"
>      android:layout_height="match_parent"
>      android:fitsSystemWindows="true">
> 
>      
> 
>      <android.support.design.widget.NavigationView
>          android:id="@+id/navigation"
>          android:layout_width="wrap_content"
>          android:layout_height="match_parent"
>          android:layout_gravity="start"
>          app:menu="@menu/my_navigation_items" />
>  </android.support.v4.widget.DrawerLayout>
> ```

**Comment by VishalNehra** [comment]
But we don't use menu resource for navigation drawer, do we?

**Comment by EmmanuelMess** [comment]
This is the view, not the menu resource, and we do use the view (in XML).

**Comment by VishalNehra** [comment]
It won't... Regardless, I set that width in past after consulting various sources and through various feedbacks of users. Changing width to 280dp might be according to guidelines as told by @TranceLove but it might ruin UX.

**Comment by EmmanuelMess** [comment]
And what about changing the size of the white section?

**Comment by VishalNehra** [comment]
We didn't create the white section. It's because of the difference between the default width of fragment and ````wrap_content```` width of navigation drawer. This gets fixed with a default width which we've been using for long enough.
What else do you propose?

**Comment by VishalNehra** [comment]
Looks too narrow.

**Comment by EmmanuelMess** [comment]
Does it cut text? If that isn't the case I would vote for the guidelines' measures.

**Comment by VishalNehra** [comment]
It doesn't but looks ugly. Like I said, many google apps themselves use this instead of guidelines's.

**Comment by EmmanuelMess** [comment]
The other option seems to be `screen width - appbar height`, this is what you prefer, right? Could you provide screenshots?

**Comment by VishalNehra** [comment]
Please create another PR if you feel like changing the drawer width, we'll discuss about it there. This one is focused on fixing what seems to be broken.

**Comment by EmmanuelMess** [comment]
Ok, I'll merge as a fix, and create an issue to follow the Design Guidelines, because I don't think I'll have the time to create a PR.

**Pull request merged**
