### PR TITLE
Test on-demand artifact generation

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
Test pr to check on-demant job running checkout on master or this PR branch.

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build artifact

**Comment by TranceLove** [comment]
Build artifact

**Comment by TranceLove** [comment]
Update code (d7d592f) can trigger Github action to build, and the magic word "Build artifact" can also trigger Github to build installable packages, that can successfully install on Oneplus 2 running AOSPExtended (7.1.2).

However I couldn't see the extra `Toast` we made at `MainActivity`... is it just me, or is it still pulling code from `master`?

**Comment by VishalNehra** [comment]
Yep, still pulling the code from master. Seems like 
```on:
  release:
    types: [published, created]
```
Action doesn't tell checkout action to checkout from PR branch instead of picking master.

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build artifact

**Comment by VishalNehra** [comment]
Build test apk

**Comment by TranceLove** [comment]
Build test apk

**Comment by TranceLove** [comment]
OK, makes sense to me now. +1, but will not approve since this PR is supposed to be for testing only.

**Comment by VishalNehra** [comment]
Yea.. thanks for verification (:

**Pull request closed without merging**
