### PR TITLE
Invert parameter order of saveToDatabase() for shortcut creation

### LINKED ISSUE #1527: Shortcut creation malformed, leads to crash
This is a regression in 3.3.
Repro:

Occurs on 3 Samsung devices running Android 7.1, 8.0 and 8.1

Settings>Shortcuts>Add Item
Enter  Name and valid directory path, then Create.

The shortcut Name and Directory fields are transposed, leading to simple name used as directory path. It visible in created shortcut. Subsequent tap on this shortcut cases crash.

Workaround is to edit the malformed shortcut transposing name and Directory, save the change. It saved correctly in edit dialog.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1527. Also changed variable name of the dialog textboxes for clarification.

### CODE REVIEW

**Comment by TranceLove** [comment]
@EmmanuelMess May you try 63acda3 once more? I couldn't reproduce the above symptom on my devices - Oneplus 2 running Slim7 (7.1.2), LG Nexus 5x running AOSPExtended (9.0), and GPD XD running LegacyROM (4.4.4).

**Comment by zent-co** [comment]
Tested this PR on my Nexus 5x running LineageOS (8.1.0) and on Samsung S8+ (Android Verison 9). Was able to reproduce the issue from the master branch and confirmed that the issue was fixed in this PR.

**Comment by EmmanuelMess** [comment]
@zent-co 
> Tested this PR on my Nexus 5x running LineageOS (8.1.0) and on Samsung S8+ (Android Verison 9). Was able to reproduce the issue from the master branch and confirmed that the issue was fixed in this PR.

Will take this as an approval, but next time please use the "review" button on the files changed tab, below the PR title.

**Comment by EmmanuelMess** [comment]
2 approvals, merge.

**Pull request merged**
