### PR TITLE
Bugfix/3875

### LINKED ISSUE #3875: Dialog for moving file is misplaced on tablet
**Describe the bug**

The dialog for moving a file appears in the bottom of the screen on my phone, but appears in the middle of the screen on my tablet. I think that the tablet's placement is bugged.

**Screenshots**

Phone:

Tablet:

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A 8.0 (2019, SM-T290)
 - OS: Android 11
 - Rooted: No
 - Version: 3.8.4

### PR DESCRIPTION
**Pull request by bimalkaf**
## Description
The dialog for moving a file appears in the bottom of the screen on the phone, but appears in the middle of the screen on the tablet. 
#### Issue tracker   
FIXES #3875

#### Manual tests
- [ X] Done

### CODE REVIEW

**Review by VishnuSanal — APPROVED** [review]
LGTM, nice work!

**Comment by bimalkaf** [comment]
> LGTM, nice work!

**Comment by bimalkaf** [comment]
@VishnuSanal  
Thanks 
accidently closed the PR, Now reopened.

**Comment by VishalNehra** [comment]
@VishnuSanal can you test this on tv as well?

**Comment by VishnuSanal** [comment]
> @VishnuSanal can you test this on tv as well? 

Do you mind doing? I don't own a physical TV (should create an emulator).

**Comment by VishnuSanal** [comment]
> > `@VishnuSanal` can you test this on tv as well?
> 
> `@VishalNehra` Do you mind doing? I don't own a physical TV (should create an emulator).

nvm, I did & it works fine! PFA the SS

TV

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
