### PR TITLE
SCP/SFTP dialog PEM file select intent fix for RESULT_OK code return

### PR DESCRIPTION
**Pull request by RP-RISING-STAR**
"SSH key select" intent always return -1 (RESULT_CANCELED) after file selection. Therefore onActivityResult code is not executed (SftpConnectDialog.java, line 270):
`if(SELECT_PEM_INTENT == requestCode && Activity.RESULT_OK == resultCode)`

Fix: Wrapped to chooser intent.

### CODE REVIEW

**Comment by VishalNehra** [comment]
@TranceLove somehow related to #1370 when I couldn't connect with a putty key?

**Comment by TranceLove** [comment]
Tested on Oneplus 2 running Slim7 (7.1.2). My key would immediately become unable to select as it's not recognisable as `text/plain` MIME type - I'm simply using the PEM files as is without extension, like `id_rsa`.

Is there a way to work around this? If `text/plain` is the way to go, maybe we should notify users to use `.pem` as PEM private key file extension (in addition to PuTTY's `.ppk` files)?

**Comment by RP-RISING-STAR** [comment]
@TranceLove, I like the idea with notification, because private keys are really 'text/plain'.

**Comment by TranceLove** [comment]
Not necessarily to code a toast or dialog, maybe some documentation will already do.

**Comment by RP-RISING-STAR** [comment]
As an option we can use a title parameter. Intent chooser shows a message on top of the list of applications that can be used for file selection. I put a simple "Select PEM file" message for now, but we can extend it.

**Comment by VishalNehra** [comment]
So what's the deal? can we never get a it working for ppk?
Also, if someone can direct how to generate an pem key for me to test this PR?

Logs below if  I try to get a ppk key after applying this PR, if these help

````
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err: org.bouncycastle.openssl.PEMException: unable to convert key pair: Attempt to invoke virtual method 'org.bouncycastle.asn1.pkcs.PrivateKeyInfo org.bouncycastle.openssl.PEMKeyPair.getPrivateKeyInfo()' on a null object reference
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyPair(Unknown Source:76)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$JcaPemToKeyPairConverter.throwingConvert(PemToKeyPairTask.java:207)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$PemToKeyPairConverter.convert(PemToKeyPairTask.java:191)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:106)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:67)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-11-28 00:39:14.696 3743-5711/com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.asn1.pkcs.PrivateKeyInfo org.bouncycastle.openssl.PEMKeyPair.getPrivateKeyInfo()' on a null object reference
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyPair(Unknown Source:0)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err: 	... 10 more
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err: java.io.IOException: Could not read key pair from: [PrivateKeyReaderResource] java.io.StringReader@495c774
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at net.schmizz.sshj.userauth.keyprovider.PKCS8KeyFile.readKeyPair(PKCS8KeyFile.java:96)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at net.schmizz.sshj.userauth.keyprovider.OpenSSHKeyFile.getPublic(OpenSSHKeyFile.java:55)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$OpenSshPemToKeyPairConverter.throwingConvert(PemToKeyPairTask.java:216)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$PemToKeyPairConverter.convert(PemToKeyPairTask.java:191)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:106)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:67)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-11-28 00:39:14.697 3743-3779/com.amaze.filemanager E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-11-28 00:39:14.697 3743-5711/com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.checkHeader(OpenSSHKeyV1KeyFile.java:167)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:72)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$OpenSshV1PemToKeyPairConverter.throwingConvert(PemToKeyPairTask.java:225)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask$PemToKeyPairConverter.convert(PemToKeyPairTask.java:191)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:106)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.asynctasks.ssh.PemToKeyPairTask.doInBackground(PemToKeyPairTask.java:67)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-11-28 00:39:14.698 3743-5711/com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
````

**Comment by RP-RISING-STAR** [comment]
@VishalNehra if you have a Linux VM just find "~/.ssh/id_rsa" in your home directory. It is in PEM format (plain text).

**Comment by RP-RISING-STAR** [comment]
You can use Putty to convert PEM to PPK (Putty Private Key) format.

**Comment by VishalNehra** [comment]
My original question was, I wanted to test this PR, so this one fixes the null return when we choose a PEM file, right? I don't think I would need puttygen to convert it to ppk, because as you suggested above, ppk files are not yet supported.

**Comment by RP-RISING-STAR** [comment]
@VishalNehra, you absolutely correct. The fix is to return RESULT_OK status when file is selected.

**Comment by TranceLove** [comment]
Is there a way so my private keys generated with `ssh-keygen` can be recognized from the intent's select file window? I already changed the key's file extension to `.pem`, but still no avail.

Unless absolutely necessary, I'm not going to convert them to PuTTY private keys since they had been working well with Amaze.

**Comment by TranceLove** [comment]
@RP-RISING-STAR I'm raising a PR to you on this changeset, so the Intent to open Android's file browser (`Intent.ACTION_GET_CONTENT` or `Intent.ACTION_OPEN_DOCUMENT`) can filter PEM files now.

However, I still haven't got an idea so the Intent can filter PuTTY keys (.ppk files) too.

Two choices (both happens after merging my PR to @RP-RISING-STAR's PR):
* Accept this PR and make the key select button to use [material-dialog's file browser](https://github.com/afollestad/material-dialogs#file-choosers) in a new PR. This can be done by anyone then
* Find a way so when `Intent.ACTION_GET_CONTENT` or `Intent.ACTION_OPEN_DOCUMENT` opens the file browser, PPK files can be selected alongside with PEM files before I accept this PR

**Comment by EmmanuelMess** [comment]
This would require some refactoring to be merged, closing, if anyone wants to merge, please open a new pr.

**Pull request closed without merging**
