### PR TITLE
Add back missing database upgrades for UtilitiesDatabase

### LINKED ISSUE #2111: Missing database migrations for earlier versions
Some users from pre-3.5 reported they are unable to start app, due to missing database migrations as seen in their logcat.

Specifically, it was `ExplorerDatabase` or its predecessor `TabHandler` which contained only migrations from 6 to 7.

Quick workaround is to do a clean install; the other way around is to trace back the migration changes all the way back, mostly in TabHandler.

### LINKED ISSUE #2114: IllegalStateException: A migration from 5 to 7 was required but not found.
```
{
  "request": "Application crash",
  "user_action": "UI Error",
  "product": "OnePlus5",
  "package": "com.amaze.filemanager",
  "os": "Linux Android 10 - 29",
  "model": "ONEPLUS A5000",
  "time": "2020-12-03 15:23",
  "version": "3.5.1",
  "device": "OnePlus5",
  "exceptions": "[java.lang.IllegalStateException: A migration from 5 to 7 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.\n\tat androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)\n\tat android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)\n\tat android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)\n\tat androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)\n\tat androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)\n\tat androidx.room.RoomDatabase.query(RoomDatabase.java:324)\n\tat androidx.room.util.DBUtil.query(DBUtil.java:83)\n\tat com.amaze.filemanager.database.daos.TabDao_Impl$7.call(TabDao_Impl.java:187)\n\tat com.amaze.filemanager.database.daos.TabDao_Impl$7.call(TabDao_Impl.java:184)\n\tat androidx.room.RxRoom$5.subscribe(RxRoom.java:229)\n\tat io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)\n\tat io.reactivex.Single.subscribe(Single.java:3603)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\n]",
  "user_comment": ""
}
```

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2111
Fixes #2114

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Additional Info

Intentionally separated into 2 commits to indicate the changes occurred, after reading commit histories, as documentation.

### CODE REVIEW

**Review by VishalNehra — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]

**Comment by EmmanuelMess** [comment]
This should be merged to a 3.5.2 branch probably.

**Comment by VishalNehra** [comment]
@EmmanuelMess Yes. Will rebase and create 3.5.2 later today

**Comment by EmmanuelMess** [comment]
@VishalNehra 3.5.2 can now be create I think, just merged 3.5.1 to master.

**Comment by VishalNehra** [comment]
@EmmanuelMess Build failing on master with test case failure. Have to fix before before creating new branch. Had rerun the job.

**Pull request merged**
