### PR TITLE
Vectorized drawer and bottom bar

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Vectorized drawer (used new, better icons, library type) and bottom bar.
* Deleted unused image.
* Rewrote Icons class.
* Deleted grid views.

### CODE REVIEW

**Comment by VishalNehra** [comment]
There's no placeholder icon for images/videos/other generic types in case the thumbnail fails to load.

**Comment by EmmanuelMess** [comment]
Where was that? The thing is I believe that the code keeps working as it did before, where's the 'transcription' error?

**Comment by EmmanuelMess** [comment]
Could you retest (and not put issues that aren't created with this pr)?

**Comment by EmmanuelMess** [comment]
As per @VishalNehra agreement this PR will be pulled.

**Pull request merged**
