### PR TITLE
Fix and optimize animations

### PR DESCRIPTION
**Pull request by EmmanuelMess**
I broke animations accidentally in commit 0d47293.

### CODE REVIEW

**Comment by VishalNehra** [comment]
I'm getting FC when fast scrolling in a big directory. And checkbox animation is still flawed when selecting/de-selecting multiple items multiple times.

**Comment by EmmanuelMess** [comment]
FC?

**Comment by EmmanuelMess** [comment]
Logcat of fast scrolling crash, it has been reported here #642
```
12-03 00:30:18.845 com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.amaze.filemanager, PID: 32392
                                                           java.util.ConcurrentModificationException
                                                               at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                               at java.util.HashMap$EntryIterator.next(HashMap.java:824)
                                                               at java.util.HashMap$EntryIterator.next(HashMap.java:824)
                                                               at com.amaze.filemanager.ui.icons.IconHolder$1.processResult(IconHolder.java:110)
                                                               at com.amaze.filemanager.ui.icons.IconHolder$1.handleMessage(IconHolder.java:89)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by EmmanuelMess** [comment]
Glitching animations was fixed.

**Comment by VishalNehra** [comment]
You say glitching animations were fixed but you didn't add the commits to this PR =_=

**Comment by EmmanuelMess** [comment]
I rebase.

**Pull request merged**
