### PR TITLE
Fix issue #1061 #1828

### LINKED ISSUE #1061: Drawer at landscape mode can drag to reveal white background
Attempt to close the drawer at landscape mode will reveal the white background beneath.

Halfway closing the drawer
screenshot_20180226-144732
Afterwards,
screenshot_20180226-145045

Not related to #1060 - same symptom came up with or without it.

### LINKED ISSUE #1828: File size shown vertically when not enough space
**Describe the bug**
When there is not enough screen space to display the file size completely, it is shown in a vertical manner. It looks awkward and also makes one file entry take up a lot of space.

**To Reproduce**
1. Go to a file which has not been modified in this year (thus resulting in the complete modification date shown)

**Expected behavior**
The file size is show in a horizontal way which is readable to users.

**Screenshots**
Screenshot_2020-01-24-08-33-23

**Smartphone (please complete the following information):**
 - Device: Samsung SM-J111F
 - OS: Android 5.1.1
 - Rooted: Yes
 - Version: 3.4.1

### PR DESCRIPTION
**Pull request by ArpitShukIa**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1061 
Fixes #1828
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Realme 3 Pro
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew spotlessCheck`
- [x] `./gradlew assembledebug`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Review by TranceLove — APPROVED** [review]

**Review by TranceLove — APPROVED** [review]
Looks OK on Fairphone 3 running LineageOS 16.0 (9.0), Oneplus 2 running AOSPExtended (7.1.2) and Samsung Galaxy S2 running SlimLP (5.1.1), drawer kept open without being able to close when in landscape while still closable when going back to portrait mode. Voting +1.

**Comment by VishalNehra** [comment]
Following code works as well in keeping the layout locked. 
Idea is to look for tab_frame view presence. The logic was already there, just needed some fix. 
Please check from your side once if this works or no.
Drawer#201-209
```
if (mainActivity.findViewById(R.id.tab_frame) != null) {
      isOnTablet = true;
      lock(DrawerLayout.LOCK_MODE_LOCKED_OPEN);
      mDrawerLayout.setScrimColor(Color.TRANSPARENT);
      mDrawerLayout.post(this::open);
    } else {
      unlockIfNotOnTablet();
      mDrawerLayout.post(this::close);
    }
```

**Comment by ArpitShukIa** [comment]
I did spend some time analyzing this part of the code and it seemed to be working fine to me. It was locking the drawer properly. I think that some other part of the code was unlocking the drawer. I tried hard but wasn't able to find the real culprit. And so I proposed a workaround which does solve the problem.

**Comment by VishalNehra** [comment]
I do understand you point.
But removing some useless method calls.. and it started working fine for me. 
The code I quoted, you can give a shot.. logically it's fine and is working for me as well.

**Pull request merged**
