### PR TITLE
Fixed placeholders when loading images 

### LINKED ISSUE #890: Glide doesn't show placeholder or failure images
When Glide is loading or when it failed to load it doesn't show a different image.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Fixed placeholders when loading images, videos and APKs. 
* Added "broken" icon for images.

The only glitch is that when in list view the placeholder always shows in a circular view.

Fixes #890

### CODE REVIEW

**Comment by VishalNehra** [comment]
The broken icon is showing strange behavior when we select it or any other item in the adapter.

**Comment by EmmanuelMess** [comment]
I tested broken images only, and it was showing the correct icon, will retest.

**Comment by EmmanuelMess** [comment]
Broken image:

PS: will fix selecting bug.

**Comment by VishalNehra** [comment]
Oh, ok my bad while testing.

**Comment by EmmanuelMess** [comment]
Fixed selecting bug with a glorified hack. I'll make an issue to fix the underlying structure.

**Comment by VishalNehra** [comment]
The issue seem to be fixed but still, selection of broken icon doesn't grey the background, instead changes it to accent color.

**Comment by EmmanuelMess** [comment]
> The issue seem to be fixed but still, selection of broken icon doesn't grey the background, instead changes it to accent color.

I didn't know it should _grey_ the background... Fixing

**Comment by EmmanuelMess** [comment]
There you go, as gray as my hat.

**Comment by VishalNehra** [comment]
I didn't mean to grey the icon by default, just for the selection color.

**Pull request merged**
