### PR TITLE
Preet90 shortcut issue

### PR DESCRIPTION
**Pull request by VishalNehra**

### CODE REVIEW

**Comment by VishalNehra** [comment]
@preet90 I can't seem to add shortcut on my Nexus 6p running Oreo. Please look into it.
Here's system log during the process as application log doesn't throw any error.

````
11-08 17:28:27.825 767-3721/? W/ShortcutService: Re-publishing ShortcutInfo returned by server is not supported. Some information such as icon may lost from shortcut.
````

**Comment by EmmanuelMess** [comment]
Also rebase into less commits with more meaningful titles, (for example: "android 8 shortcuts working" + "Now the shortcuts are updating once the shortcut buffer is full." + "added the mimetype for the files without the extension" + "formatted the code." -> "Reworked shortcuts for Android 8").

**Comment by preet90** [comment]
@VishalNehra I will have a look at this.

**Comment by EmmanuelMess** [comment]
To maintain a clean project I will close this PR and reopen #818. I will delete `TeamAmaze/preet90-shortcut-issue` in a week. You should `git cherry-pick 12ca873` from your repository or modify your commits appropriately.

**Pull request closed without merging**
