### PR TITLE
New search window with library

### PR DESCRIPTION
**Pull request by EmmanuelMess**
#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishnuSanal — APPROVED** [review]
LGTM 🚀

**Comment by VishalNehra** [comment]
Issues:
1. Orientation of hint text doesn't seem right. Previous one was inline with other content below it.
2. it doesn't indicate that it's currently selected, normally edittext has an underline when we're typing in it.
3. Also there's a strange black border around the whole view when we're typing.
4. Heigh of whole bar seem to be smaller than previous one.

Please refer to screenshots for comparison.
Screenshot_20220327-022637__01
Screenshot_20220327-022701
Screenshot_20220327-022637
Screenshot_20220327-022640
Screenshot_20220327-022139

**Comment by EmmanuelMess** [comment]
@VishalNehra the bar things is weird, I'll try to replicate, otherwise it is up to Material Design standards: see https://material.io/design/navigation/search.html#persistent-search.

**Comment by EmmanuelMess** [comment]
@TranceLove I am not quite sure what broke here, any ideas?

**Comment by EmmanuelMess** [comment]
Any news?

**Comment by VishalNehra** [comment]
Will check today.

**Comment by VishalNehra** [comment]
Getting following crash when i rotate my screem

## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager.debug
* __Version:__ 3.6.7
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux OnePlus/OnePlus9R_IND/OnePlus9R:11/RKQ1.201112.002/2201212022:user/release-keys 11 - 30
* __Device:__ OnePlus9R
* __Model:__ LE2101
* __Product:__ OnePlus9R_IND
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
	at com.amaze.filemanager.ui.views.appbar.SearchView.hideSearchView(SearchView.kt:120)
	at com.amaze.filemanager.ui.views.appbar.SearchView$3.onFocusCleared(SearchView.kt:67)
	at xyz.quaver.floatingsearchview.FloatingSearchView.setSearchFocused(FloatingSearchView.kt:196)
	at xyz.quaver.floatingsearchview.FloatingSearchView.onRestoreInstanceState(FloatingSearchView.kt:811)
	at android.view.View.dispatchRestoreInstanceState(View.java:20890)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4011)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.View.restoreHierarchyState(View.java:20868)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2204)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1383)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3664)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8030)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Rejecting this due to new search ui in #3730

**Pull request closed without merging**
