### PR TITLE
Remove log message truncation in Github CI actions

### LINKED ISSUE #2717: Running tests seems to have broken
Lately tests for PR have not been running, there are issues downloading correct files, and compilation errors, but the CI passes for some reason.

https://github.com/TeamAmaze/AmazeFileManager/runs/3231527608#step:6:1212

I cannot get the tests to run on my PC either.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #2717.

In fact, it seems [only we truncate log messages](https://github.com/search?l=YAML&q=gradlew+spotlessCheck+grep&type=Code).

### CODE REVIEW

**Comment by VishalNehra** [comment]
> Codacy fails?

Yes, I commit wrong format intentionally but notice how even after codacy fails the build continues to other steps.

**Comment by EmmanuelMess** [comment]
> > Codacy fails?
> 
> No, spotless failure, I commit wrong format intentionally but notice how even after spotlessCheck fails the build continues to other steps.

image

This is a spotless failure?

**Comment by VishalNehra** [comment]
> > > Codacy fails?
> > 
> > 
> > No, spotless failure, I commit wrong format intentionally but notice how even after spotlessCheck fails the build continues to other steps.
> 
> image
> 
> This is a spotless failure?

Check the spotless step logs, it failed there and then, but the build still continued. Publish test cases fails because there's no coverage xml generated because test cases step also failed (but build still continued).

**Comment by TranceLove** [comment]
357f6ac build failed not because of test failures, but codacy couldn't find the test report.

From 0fc680b it seems removing all those `grep -vE` calls may be a help to the problem...

**Comment by VishalNehra** [comment]
> From [0fc680b](https://github.com/TeamAmaze/AmazeFileManager/commit/0fc680bfd6c9f87bdfd6867cba0bf9050973b8ae) it seems removing all those `grep -vE` calls may be a help to the problem...

That's what I was coming at conclusion, because the grep output is somehow masking the gradle build output. I tried in local but it didn't mask, not sure why the github build decides the build as passing :/

**Review by EmmanuelMess — DISMISSED** [review]

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
