### PR TITLE
Feature: floating action button for selection of multiple files

### LINKED ISSUE #3747: Selection of multiple files
I can use Amaze to select files for upload (e.g. to Jira from browser), but it only offers to select one file at a time. Other file managers (e.g. default Samsung MyFiles, or XFolder) allow me to select multiple files for upload.
I'd like this feature in Amaze as well.

### PR DESCRIPTION
**Pull request by seelchen**
## Description
This PR adds a floating action button to confirm your selection when Amaze is opened as a file picker by another app.

https://github.com/TeamAmaze/AmazeFileManager/assets/74261221/5d81bd9a-74f7-46a3-9ed9-29797f2b7237

When only one file can be selected, the selection switches between the clicked files.

https://github.com/TeamAmaze/AmazeFileManager/assets/74261221/64242b3c-39e2-47d7-a357-c7e0876b9fe0

#### Issue tracker   

Fixes #3747

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done 

Device: 
- Pixel 7 emulator running Android 13
- HTC U11 life running Android 10
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
This is still a wip?

**Comment by seelchen** [comment]
Yes, I wanted to check something with the select all button. But I should be finished this evening (UTC+2).

**Comment by seelchen** [comment]
This PR is ready for review! I don't know why the Jacoco tests fail, when I run them locally, they all pass...

**Comment by VishnuSanal** [comment]
> This PR is ready for review! I don't know why the Jacoco tests fail, when I run them locally, they all pass...

the test passed on second attempt. consider the old failure as a false trigger. :)

**Review by VishnuSanal — APPROVED** [review]
awesome work! works as expected.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
