### PR TITLE
Made most Parcelables mostly immutable

### PR DESCRIPTION
**Pull request by EmmanuelMess**
So that one can get fields directly instead of using getter.

### CODE REVIEW

**Comment by VishalNehra** [comment]
This is against the [best practices](http://www.codejava.net/coding/java-getter-and-setter-tutorial-from-basics-to-best-practices) for java style coding, and shall not be utilized wherever possible.
However, you can try to tackle some problems mentioned with our implementation of getter/setter as given in this link.

**Comment by EmmanuelMess** [comment]
You can't change a final value, setters make no sense, and getters are redundant, why would you need them? Check Pair and Java immutables

**Comment by VishalNehra** [comment]
@EmmanuelMess that is purely subjective and depends on the requirement. 
For GUI programming, like ours, it's always better to keep objects mutable.

**Comment by EmmanuelMess** [comment]
@VishalNehra Why? I makes for less code to have immutables.

**Comment by VishalNehra** [comment]
Really? You'll have to create new objects each time user make any interaction with GUI. Not to mention, cloning existing data to new object will just extend the code more.  While a simple setter method can do this job. I do agree immutables are really helpful for concurrent programming, hence will be useful for some parts of our project, but that doesn't mean you make all your objects immutable. 
There's a thing called MVC for a reason. Otherwise they would also have simply used immutables instead of creating models for each component.

**Comment by EmmanuelMess** [comment]
There's no need for setters in the majority of these. They are just created to hold some data and then get destroyed.

**Comment by EmmanuelMess** [comment]
Maybe I can just Kotlinize... That sounds better?

**Comment by VishalNehra** [comment]
Alright, can be pulled, but please rebase this branch first.

**Comment by EmmanuelMess** [comment]
Done.

**Pull request merged**
