### PR TITLE
Fixed app crash in ROOT mode

### LINKED ISSUE #2271: Crash reported by Thomas
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux Android 10 - 29
* __Device:__ taimen
* __Model:__ Pixel 2 XL
* __Product:__ taimen
Crash log

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String androidx.documentfile.provider.DocumentFile.getName()' on a null object reference
at com.amaze.filemanager.filesystem.HybridFile.getName(HybridFile.java:336)
at com.amaze.filemanager.filesystem.Operations$1.doInBackground(Operations.java:122)
at com.amaze.filemanager.filesystem.Operations$1.doInBackground(Operations.java:115)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more

```

----------------------------------------

### PR DESCRIPTION
**Pull request by ShivanshGoel221B**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2271 

#### Release  
Addresses release/
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Nokia 5.3
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
I added a test for the null object at HybridFile.java line 336.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
What happens when getName() returns null?

**Comment by ShivanshGoel221B** [comment]
> What happens when getName() returns null?

Then it runs the default block and returns the variable name.

**Comment by EmmanuelMess** [comment]
> Then it runs the default block and returns the variable name.

No, it doesn't, it moves to the next case, here it is the `case OTG:`.

**Comment by ShivanshGoel221B** [comment]
> > Then it runs the default block and returns the variable name.
> 
> No, it doesn't, it moves to the next case, here it is the `case OTG:`.

Yeah, I meant that if only ROOT case mathes and yet it is null, then it returns the name otherwise it will check for the next cases.

**Comment by EmmanuelMess** [comment]
> > > Then it runs the default block and returns the variable name.
> > 
> > 
> > No, it doesn't, it moves to the next case, here it is the `case OTG:`.
> 
> Yeah, I meant that if only ROOT case mathes and yet it is null, then it returns the name otherwise it will check for the next cases.

If mode is ROOT or mode is FILE, and getFile().getName() == null, it will try to open the file as OTG USB and instacrash.

**Comment by ShivanshGoel221B** [comment]
> > > > Then it runs the default block and returns the variable name.
> > > 
> > > 
> > > No, it doesn't, it moves to the next case, here it is the `case OTG:`.
> > 
> > Yeah, I meant that if only ROOT case mathes and yet it is null, then it returns the name otherwise it will check for the next cases.
> 
> If mode is ROOT or mode is FILE, and getFile().getName() == null, it will try to open the file as OTG USB and instacrash.

Well, if the mode is ROOT or FILE then the OTG case would not be matched and yet the default case gets executed.

**Comment by EmmanuelMess** [comment]
@VishalNehra please provide a 3rd point of view, thanks.

**Pull request closed without merging**
